import type { SeedRow } from '@/lib/seed-data';

// Auto-generated from ecomatrix-all-leads.csv in rank order (585 resolved leads).
// Rows marked 'Needs lookup' in other-niche-classification.csv are intentionally skipped.
export const CALL_LIST: SeedRow[] = [
  { businessName: "Tommy's Heating & Air", niche: "hvac", city: "Webb", state: "AL", phone: "(334) 792-8338", rating: 4.9, reviewCount: 177 },
  { businessName: "Rogers Mechanical Heating And Cooling", niche: "hvac", city: "Huntsville", state: "ON", phone: "(705) 706-1079", rating: 4.9, reviewCount: 84 },
  { businessName: "Jackson Heating & Air Conditioning, LLC", niche: "hvac", city: "Greenville", state: "MS", phone: "(662) 332-0420", rating: 4.9, reviewCount: 83 },
  { businessName: "Steve Daves Heating & Air, LLC", niche: "hvac", city: "Greenwood", state: "MS", phone: "(662) 453-0609", rating: 5, reviewCount: 63 },
  { businessName: "Walker Ac and Heating", niche: "hvac", city: "D'Iberville", state: "MS", phone: "(228) 209-0682", rating: 4.5, reviewCount: 60 },
  { businessName: "AC Man Heating & Air Conditioning", niche: "hvac", city: "Ocean Springs", state: "MS", phone: "(228) 875-4487", rating: 4.2, reviewCount: 58 },
  { businessName: "Garcia Roofing & Construction", niche: "roofing", city: "Wichita Falls", state: "TX", phone: "(940) 642-6558", rating: 5, reviewCount: 55 },
  { businessName: "Gary's Sewer & Drain", niche: "plumbing", city: "Pocatello", state: "ID", phone: "(208) 232-7464", rating: 4.9, reviewCount: 41 },
  { businessName: "Troyer Roofing", niche: "roofing", city: "Libby", state: "MT", phone: "(406) 334-0500", rating: 4.8, reviewCount: 39 },
  { businessName: "Top Priority Drain Cleaning", niche: "septic", city: "", state: "WY", phone: "(307) 709-2564", rating: 4.9, reviewCount: 33 },
  { businessName: "Sterling Excavation Sewer services", niche: "excavating", city: "Casper", state: "WY", phone: "(307) 258-5381", rating: 4.7, reviewCount: 29 },
  { businessName: "Saurer's Pump Services", niche: "well_water", city: "Missoula", state: "MT", phone: "(406) 543-3654", rating: 5, reviewCount: 21 },
  { businessName: "Yardworks | Landscaping & Tree Removal", niche: "tree", city: "Middle River", state: "NB", phone: "(506) 543-0591", rating: 4.4, reviewCount: 20 },
  { businessName: "J Marshall's Heating", niche: "hvac", city: "Warren Grove", state: "PE", phone: "(902) 569-9169", rating: 4.4, reviewCount: 11 },
  { businessName: "Done Right Heating &AC", niche: "hvac", city: "Ridgeland", state: "MS", phone: "(601) 895-0222", rating: 5, reviewCount: 471 },
  { businessName: "Jackson's Favorite Air Conditioning", niche: "hvac", city: "Jackson", state: "MS", phone: "(769) 214-2654", rating: 4.9, reviewCount: 204 },
  { businessName: "ASAP Septic Pumping LLC", niche: "septic", city: "", state: "ID", phone: "(208) 390-7559", rating: 5, reviewCount: 153 },
  { businessName: "Comfortable Climates Heating & Air", niche: "hvac", city: "Kokomo", state: "IN", phone: "(765) 461-1930", rating: 5, reviewCount: 123 },
  { businessName: "Masters Well & Pump Service", niche: "well_water", city: "Hayden", state: "ID", phone: "(208) 660-4134", rating: 5, reviewCount: 104 },
  { businessName: "Albreeze Air Conditioning, Refrigeration & Mechanical Contractor", niche: "hvac", city: "", state: "", phone: "(242) 477-1341", rating: 4.9, reviewCount: 57 },
  { businessName: "Vertical Tree Co. LLC", niche: "tree", city: "Blackfoot", state: "ID", phone: "(208) 244-9967", rating: 4.6, reviewCount: 48 },
  { businessName: "ASAP Septic", niche: "septic", city: "Melba", state: "ID", phone: "(208) 991-7184", rating: 5, reviewCount: 47 },
  { businessName: "Top Notch Tree Service LLC", niche: "tree", city: "Priest River", state: "ID", phone: "(208) 627-6035", rating: 5, reviewCount: 42 },
  { businessName: "Marion Heating & Cooling Inc", niche: "hvac", city: "Marion", state: "IA", phone: "(319) 304-1397", rating: 4.9, reviewCount: 37 },
  { businessName: "L&C Heating and Cooling", niche: "hvac", city: "Conover", state: "WI", phone: "(715) 479-2539", rating: 4.4, reviewCount: 37 },
  { businessName: "Affordable Septic Tank Pumping", niche: "septic", city: "Idaho Falls", state: "ID", phone: "(208) 569-8219", rating: 4.9, reviewCount: 37 },
  { businessName: "Marlatt Tree Care LLC", niche: "tree", city: "", state: "WY", phone: "(307) 331-5102", rating: 5, reviewCount: 36 },
  { businessName: "Air Pro Heating And Cooling", niche: "hvac", city: "Metropolis", state: "IL", phone: "(270) 816-0825", rating: 4.2, reviewCount: 36 },
  { businessName: "Redhorn Pump Service Inc.", niche: "well_water", city: "St Ignatius", state: "MT", phone: "(406) 676-7867", rating: 5, reviewCount: 33 },
  { businessName: "Keller Roofing", niche: "roofing", city: "Sioux Falls", state: "SD", phone: "(605) 362-1100", rating: 5, reviewCount: 33 },
  { businessName: "JH Excavation Inc.", niche: "excavating", city: "Powell", state: "WY", phone: "(307) 689-3369", rating: 5, reviewCount: 31 },
  { businessName: "Eckert's Patriot Pumpers", niche: "septic", city: "", state: "MT", phone: "(406) 777-2816", rating: 4.7, reviewCount: 28 },
  { businessName: "Up North Heating & Air Conditioning Ltd.", niche: "hvac", city: "Latchford", state: "ON", phone: "(705) 622-8978", rating: 5, reviewCount: 27 },
  { businessName: "CDN Fence Company", niche: "fence", city: "Post Falls", state: "ID", phone: "(509) 201-2548", rating: 4.8, reviewCount: 26 },
  { businessName: "Part Time HVAC LLC", niche: "hvac", city: "Hardy", state: "AR", phone: "(870) 710-2200", rating: 4.7, reviewCount: 26 },
  { businessName: "Busy Boys Stump Grinding & Tractor Work", niche: "tree", city: "Blackfoot", state: "ID", phone: "(208) 200-4429", rating: 5, reviewCount: 24 },
  { businessName: "Success Septic Tank Service", niche: "septic", city: "", state: "ID", phone: "(208) 428-0079", rating: 4.4, reviewCount: 22 },
  { businessName: "Carroll Septic Services", niche: "septic", city: "Riverton", state: "WY", phone: "(307) 856-3708", rating: 4.3, reviewCount: 21 },
  { businessName: "Tier One Fence Company", niche: "fence", city: "", state: "MT", phone: "(406) 694-8143", rating: 5, reviewCount: 20 },
  { businessName: "Forrest's Tree Service", niche: "tree", city: "Twin Falls", state: "ID", phone: "(208) 212-3690", rating: 4.4, reviewCount: 18 },
  { businessName: "Triple J Pumping", niche: "septic", city: "Cheyenne", state: "WY", phone: "(307) 632-6476", rating: 4.7, reviewCount: 17 },
  { businessName: "A C Tree Service", niche: "tree", city: "Casper", state: "WY", phone: "(307) 234-7353", rating: 4.4, reviewCount: 14 },
  { businessName: "Hal Lee Plumbing & Heating", niche: "plumbing", city: "", state: "WY", phone: "(307) 587-3134", rating: 3.5, reviewCount: 13 },
  { businessName: "Rock Creek Well Services", niche: "well_water", city: "Cheyenne", state: "WY", phone: "(307) 630-6617", rating: 3.8, reviewCount: 13 },
  { businessName: "All Seasons Tree Services-Anaconda", niche: "tree", city: "Anaconda", state: "MT", phone: "(406) 560-6587", rating: 4.7, reviewCount: 12 },
  { businessName: "Smith Septic Pumping Ronan", niche: "septic", city: "Ronan", state: "MT", phone: "(406) 675-2050", rating: 4.2, reviewCount: 12 },
  { businessName: "Darrell Adams Tree Service", niche: "tree", city: "Blackfoot", state: "ID", phone: "(208) 840-9457", rating: 4.9, reviewCount: 12 },
  { businessName: "TR Excavation, LLC", niche: "excavating", city: "Cataldo", state: "ID", phone: "(208) 682-5092", rating: 4, reviewCount: 12 },
  { businessName: "Anderson Pump & Well Service, Inc", niche: "well_water", city: "Bigfork", state: "MT", phone: "(406) 837-1665", rating: 5, reviewCount: 11 },
  { businessName: "B & C Property Care", niche: "fence", city: "Evansville", state: "WY", phone: "(307) 265-9473", rating: 5, reviewCount: 11 },
  { businessName: "Frederick's Vacuum Truck Service", niche: "septic", city: "", state: "WY", phone: "(307) 247-0357", rating: 5, reviewCount: 11 },
  { businessName: "RB Lewis Tree Service", niche: "tree", city: "", state: "WY", phone: "(307) 209-1339", rating: 5, reviewCount: 10 },
  { businessName: "Scott Ganoe Tree & Landscape", niche: "tree", city: "Heyburn", state: "ID", phone: "(208) 438-2485", rating: 4.5, reviewCount: 10 },
  { businessName: "A & A Septic Service, Inc.", niche: "septic", city: "", state: "ID", phone: "(208) 476-9143", rating: 5, reviewCount: 10 },
  { businessName: "Solid Ground Excavating", niche: "excavating", city: "Lolo", state: "MT", phone: "(406) 381-5066", rating: 5, reviewCount: 9 },
  { businessName: "LB Lawn & Fencing", niche: "fence", city: "Missoula", state: "MT", phone: "(406) 370-7026", rating: 5, reviewCount: 7 },
  { businessName: "Elison Excavation", niche: "excavating", city: "Blackfoot", state: "ID", phone: "(208) 604-3716", rating: 4.3, reviewCount: 6 },
  { businessName: "Brewster Construction & Excavating", niche: "excavating", city: "Kila", state: "MT", phone: "(406) 249-9923", rating: 5, reviewCount: 6 },
  { businessName: "7B Stump Removal", niche: "tree", city: "", state: "ID", phone: "(208) 255-7832", rating: 5, reviewCount: 6 },
  { businessName: "Bethers Excavation", niche: "excavating", city: "", state: "ID", phone: "(208) 540-2640", rating: 5, reviewCount: 6 },
  { businessName: "Rocky Mountain Septic Services", niche: "septic", city: "Helena", state: "MT", phone: "(406) 459-4325", rating: 4.7, reviewCount: 6 },
  { businessName: "Millikin Well Drilling", niche: "well_water", city: "Glendo", state: "WY", phone: "(307) 331-2398", rating: 4.4, reviewCount: 5 },
  { businessName: "Huckleberry Earth Works", niche: "excavating", city: "Corvallis", state: "MT", phone: "(406) 529-0854", rating: 5, reviewCount: 5 },
  { businessName: "Ed's Auto Wrecking", niche: "landscaping", city: "Casper", state: "WY", phone: "(307) 472-3558", rating: 4.2, reviewCount: 125 },
  { businessName: "Aguilar's Truck & Trailer Washout", niche: "pressure_wash", city: "American Falls", state: "ID", phone: "(208) 240-2698", rating: 4.5, reviewCount: 89 },
  { businessName: "Faithful Pressure Wash", niche: "pressure_wash", city: "", state: "MT", phone: "(406) 697-0192", rating: 5, reviewCount: 74 },
  { businessName: "GreenCare North", niche: "landscaping", city: "Bonners Ferry", state: "ID", phone: "(208) 217-8461", rating: 4.9, reviewCount: 58 },
  { businessName: "Bullard's Landscaping & Nursery in Flora", niche: "landscaping", city: "Flora", state: "IL", phone: "(618) 231-0280", rating: 4.6, reviewCount: 57 },
  { businessName: "Pow-A-Wash LLC", niche: "pressure_wash", city: "", state: "MT", phone: "(406) 561-0866", rating: 5, reviewCount: 56 },
  { businessName: "Stittsville Landscape Repair Co.", niche: "landscaping", city: "Stittsville", state: "ON", phone: "(613) 979-0304", rating: 5, reviewCount: 49 },
  { businessName: "Mr.T's Up-keep Services LLC", niche: "landscaping", city: "Gillette", state: "WY", phone: "(307) 622-0111", rating: 5, reviewCount: 40 },
  { businessName: "A&K Hauling & Junk Removal Service LLC", niche: "junk_removal", city: "", state: "WY", phone: "(307) 670-4488", rating: 5, reviewCount: 39 },
  { businessName: "Xtreme Clean Floor Care", niche: "cleaning", city: "Rock Springs", state: "WY", phone: "(307) 922-1686", rating: 4.7, reviewCount: 22 },
  { businessName: "Point of View Landscape LLC", niche: "landscaping", city: "Benton", state: "AR", phone: "(501) 239-1923", rating: 5, reviewCount: 21 },
  { businessName: "Iconic Lawn & Tree", niche: "tree", city: "Blue Springs", state: "MO", phone: "", rating: 5, reviewCount: 82 },
  { businessName: "KTS Construction", niche: "landscaping", city: "", state: "ID", phone: "(208) 304-2376", rating: 5, reviewCount: 6 },
  { businessName: "Clint Insurance Agency", niche: "insurance", city: "Clint", state: "TX", phone: "(915) 851-0351", rating: 4.8, reviewCount: 143 },
  { businessName: "Fratesi & Co The Salon and Day Spa", niche: "beauty", city: "White Hall", state: "AR", phone: "(870) 247-3728", rating: 4.9, reviewCount: 59 },
  { businessName: "Colonel Air Conditioning", niche: "hvac", city: "", state: "", phone: "(876) 799-0341", rating: 5, reviewCount: 18 },
  { businessName: "Superior Septic Services Inc", niche: "septic", city: "Superior", state: "MT", phone: "(406) 822-4495", rating: 5, reviewCount: 17 },
  { businessName: "Big Ridge Pump and Well Drilling Service", niche: "well_water", city: "Afton", state: "WY", phone: "(307) 699-9643", rating: 5, reviewCount: 17 },
  { businessName: "Key Largo Air Conditioning & Heating", niche: "hvac", city: "Key Largo", state: "FL", phone: "(645) 600-2188", rating: 4.7, reviewCount: 15 },
  { businessName: "Berwic Heating And Cooling", niche: "hvac", city: "Bloomfield", state: "PE", phone: "(902) 719-9383", rating: 5, reviewCount: 15 },
  { businessName: "Reliable Septic Pumping LLC", niche: "septic", city: "", state: "ID", phone: "(208) 220-5928", rating: 5, reviewCount: 14 },
  { businessName: "Trejo Roofing & Construction LLC", niche: "roofing", city: "Perryton", state: "TX", phone: "(806) 202-1748", rating: 5, reviewCount: 14 },
  { businessName: "Brenda Frank Septic Tank Service", niche: "septic", city: "Laurel", state: "MT", phone: "(406) 628-7316", rating: 5, reviewCount: 13 },
  { businessName: "Bud's Septic Tank Services", niche: "septic", city: "Payette", state: "ID", phone: "(208) 642-4160", rating: 5, reviewCount: 13 },
  { businessName: "Comfortable Home Heating & Cooling", niche: "hvac", city: "Cattaraugus", state: "NY", phone: "(716) 844-1681", rating: 5, reviewCount: 13 },
  { businessName: "Alexandria Heating & Air Conditioning", niche: "hvac", city: "Alexandria", state: "MN", phone: "(320) 335-2979", rating: 5, reviewCount: 13 },
  { businessName: "Tip Top Tree Service", niche: "tree", city: "Torrington", state: "WY", phone: "(308) 623-2725", rating: 4.8, reviewCount: 12 },
  { businessName: "J & J Roofing", niche: "roofing", city: "Grand Island", state: "NE", phone: "(308) 389-6188", rating: 4.3, reviewCount: 12 },
  { businessName: "Badger Heating & Cooling Inc", niche: "hvac", city: "Three Lakes", state: "WI", phone: "(715) 546-3147", rating: 5, reviewCount: 11 },
  { businessName: "Rainbow Septic Service", niche: "septic", city: "Ronan", state: "MT", phone: "(406) 676-2400", rating: 4.3, reviewCount: 10 },
  { businessName: "Basic Maintenance LLC", niche: "tree", city: "", state: "WY", phone: "(307) 363-6525", rating: 3.7, reviewCount: 10 },
  { businessName: "Kansas City Electrical Construction Inc", niche: "electrical", city: "Kansas City", state: "MO", phone: "(816) 403-4650", rating: 4.6, reviewCount: 10 },
  { businessName: "Mr Snow It All and Tree Service", niche: "tree", city: "Billings", state: "MT", phone: "(406) 794-4438", rating: 5, reviewCount: 10 },
  { businessName: "TNT Water and Sewer", niche: "excavating", city: "", state: "MT", phone: "(406) 852-4839", rating: 5, reviewCount: 9 },
  { businessName: "Brians Quality Tree Service", niche: "tree", city: "Great Falls", state: "MT", phone: "(406) 799-1839", rating: 5, reviewCount: 9 },
  { businessName: "Monroe Fence Co", niche: "fence", city: "Chubbuck", state: "ID", phone: "(208) 237-1491", rating: 4.3, reviewCount: 6 },
  { businessName: "Karnatz Tree Services", niche: "tree", city: "Livingston", state: "MT", phone: "(406) 222-6505", rating: 4.8, reviewCount: 5 },
  { businessName: "Dalley's Sanitation", niche: "septic", city: "", state: "WY", phone: "(307) 851-9524", rating: 5, reviewCount: 5 },
  { businessName: "Harvey Roofing, Inc.", niche: "roofing", city: "St Maries", state: "ID", phone: "(208) 582-1944", rating: 5, reviewCount: 5 },
  { businessName: "Ochs Heating & Air Conditioning", niche: "hvac", city: "", state: "", phone: "(785) 421-2812", rating: 4, reviewCount: 4 },
  { businessName: "Montana Septic", niche: "septic", city: "Hardin", state: "MT", phone: "(406) 665-5772", rating: 5, reviewCount: 3 },
  { businessName: "Spruce Tree Service LLC", niche: "tree", city: "Weiser", state: "ID", phone: "(208) 869-9427", rating: 3, reviewCount: 3 },
  { businessName: "Farrier Fencing LLC", niche: "fence", city: "Polson", state: "MT", phone: "(406) 883-4197", rating: 2.3, reviewCount: 3 },
  { businessName: "B.T.E. ELECTRIC } better than edison {", niche: "electrical", city: "Kansas City", state: "MO", phone: "(816) 469-0857", rating: 3.7, reviewCount: 3 },
  { businessName: "Johnson Custom Fencing Inc", niche: "fence", city: "Butte", state: "MT", phone: "(406) 490-2860", rating: 4, reviewCount: 3 },
  { businessName: "Oil Capital Tree Service LLC", niche: "tree", city: "Casper", state: "WY", phone: "(307) 234-5474", rating: 5, reviewCount: 3 },
  { businessName: "Double T Tree Service", niche: "tree", city: "", state: "MT", phone: "(406) 853-3365", rating: 5, reviewCount: 2 },
  { businessName: "Moreno's Tree Service", niche: "tree", city: "Weiser", state: "ID", phone: "(208) 405-8953", rating: 5, reviewCount: 2 },
  { businessName: "Operation Comfort HVAC and Repair", niche: "hvac", city: "Norfolk", state: "NE", phone: "(402) 649-2902", rating: 5, reviewCount: 2 },
  { businessName: "Garreau Heating", niche: "hvac", city: "Temiskaming Shores", state: "ON", phone: "(705) 680-0117", rating: 5, reviewCount: 1 },
  { businessName: "Boyd roofing & construction", niche: "roofing", city: "Mission Hill", state: "SD", phone: "(402) 302-3613", rating: 5, reviewCount: 1 },
  { businessName: "Nolagreen Landscaping, LLC", niche: "landscaping", city: "Jefferson", state: "LA", phone: "(504) 701-4004", rating: 4.9, reviewCount: 113 },
  { businessName: "Huskie Carpet Cleaning", niche: "cleaning", city: "Fruitland", state: "ID", phone: "(208) 570-9889", rating: 4.9, reviewCount: 83 },
  { businessName: "Discount Lawncare & Landscaping", niche: "landscaping", city: "Mountain Home", state: "AR", phone: "(870) 656-5588", rating: 5, reviewCount: 79 },
  { businessName: "Irri Gators LLC", niche: "landscaping", city: "Gillette", state: "WY", phone: "(307) 660-6405", rating: 5, reviewCount: 75 },
  { businessName: "Reliable Lawn Service LLC", niche: "landscaping", city: "Mineral Wells", state: "WV", phone: "(740) 856-7042", rating: 4.9, reviewCount: 58 },
  { businessName: "Complete Lawn Care", niche: "landscaping", city: "Evanston", state: "WY", phone: "(503) 960-8057", rating: 4.8, reviewCount: 39 },
  { businessName: "A1 Haulers LLC", niche: "junk_removal", city: "Mountain Home", state: "ID", phone: "(208) 249-9054", rating: 5, reviewCount: 39 },
  { businessName: "Superior Lawn & Landscaping", niche: "landscaping", city: "Hot Springs", state: "AR", phone: "(501) 507-7963", rating: 4.5, reviewCount: 34 },
  { businessName: "Pecas Landscape & Concrete", niche: "landscaping", city: "Magnolia", state: "AR", phone: "(870) 562-1027", rating: 4.9, reviewCount: 33 },
  { businessName: "River Rock Restoration Carpet Cleaners", niche: "cleaning", city: "Butte", state: "MT", phone: "(406) 479-3504", rating: 4.8, reviewCount: 33 },
  { businessName: "The Whit Trash Man", niche: "junk_removal", city: "", state: "WY", phone: "(307) 286-2422", rating: 5, reviewCount: 32 },
  { businessName: "Mabie's Lawn & Landscaping LLC", niche: "landscaping", city: "Independence", state: "MO", phone: "(816) 352-1591", rating: 5, reviewCount: 25 },
  { businessName: "Blue Collar Pressure Wash", niche: "pressure_wash", city: "Cheyenne", state: "WY", phone: "(307) 223-2280", rating: 5, reviewCount: 25 },
  { businessName: "Clearly Seen Window Cleaning", niche: "cleaning", city: "", state: "ID", phone: "(208) 490-7553", rating: 5, reviewCount: 23 },
  { businessName: "Corner To Corner Landscaping", niche: "landscaping", city: "Moncton", state: "NB", phone: "(506) 588-6612", rating: 4.7, reviewCount: 23 },
  { businessName: "Trim Way Landscaping", niche: "landscaping", city: "Riverview", state: "NB", phone: "(506) 872-0357", rating: 4.1, reviewCount: 22 },
  { businessName: "R & R Curb and Landscape", niche: "landscaping", city: "Paynesville", state: "MN", phone: "(320) 250-7699", rating: 5, reviewCount: 22 },
  { businessName: "Heartland Landscaping Inc", niche: "landscaping", city: "Effingham", state: "IL", phone: "(217) 342-2579", rating: 4.9, reviewCount: 14 },
  { businessName: "Green Earth Landscaping, LLC", niche: "landscaping", city: "Leesburg", state: "VA", phone: "(703) 777-2210", rating: 5, reviewCount: 13 },
  { businessName: "Dirty Boyz Sanitation Service", niche: "junk_removal", city: "Rawlins", state: "WY", phone: "(307) 321-3874", rating: 4.7, reviewCount: 12 },
  { businessName: "John's Maintenance & Landscaping", niche: "landscaping", city: "Riverview", state: "NB", phone: "(506) 863-3929", rating: 4.3, reviewCount: 12 },
  { businessName: "Shimmer LLC", niche: "cleaning", city: "Twin Falls", state: "ID", phone: "(208) 316-6145", rating: 5, reviewCount: 12 },
  { businessName: "Design One Landscaping & Home Decor", niche: "landscaping", city: "Pine Bluff", state: "AR", phone: "(870) 535-5968", rating: 4.2, reviewCount: 11 },
  { businessName: "Just Call Sean Handyman LLC", niche: "handyman", city: "", state: "ID", phone: "(208) 732-9982", rating: 5, reviewCount: 10 },
  { businessName: "Route 33 Landscape Management", niche: "landscaping", city: "Nelsonville", state: "OH", phone: "(740) 216-9006", rating: 4.6, reviewCount: 10 },
  { businessName: "Rone Lawncare and Landscaping", niche: "landscaping", city: "Batesville", state: "AR", phone: "(870) 384-4284", rating: 5, reviewCount: 10 },
  { businessName: "BAKO'S Custom Lawn Care, LLC", niche: "pressure_wash", city: "", state: "ID", phone: "(208) 293-7972", rating: 5, reviewCount: 9 },
  { businessName: "Peak to Peak Pressure Washing", niche: "pressure_wash", city: "Bozeman", state: "MT", phone: "(406) 595-9656", rating: 5, reviewCount: 9 },
  { businessName: "Magic Valley Window Washing LLC", niche: "cleaning", city: "", state: "ID", phone: "(208) 749-6637", rating: 5, reviewCount: 8 },
  { businessName: "Handyman Home Repairs", niche: "handyman", city: "Miles City", state: "MT", phone: "(406) 981-1320", rating: 5, reviewCount: 7 },
  { businessName: "Dr. Lawn Care & Restoration, LLC", niche: "landscaping", city: "Brandon", state: "MS", phone: "(601) 826-1407", rating: 5, reviewCount: 6 },
  { businessName: "Big Sky Exterior Cleaning Specialists", niche: "pressure_wash", city: "", state: "MT", phone: "(406) 200-8230", rating: 5, reviewCount: 5 },
  { businessName: "TRS Landscaping", niche: "landscaping", city: "Kapuskasing", state: "ON", phone: "(289) 501-8182", rating: 5, reviewCount: 5 },
  { businessName: "Kel's Tender Lawn Care", niche: "landscaping", city: "Scott City", state: "KS", phone: "(620) 872-7325", rating: 3.4, reviewCount: 5 },
  { businessName: "Tease Salon And Colorbar", niche: "beauty", city: "Panama City", state: "FL", phone: "(850) 630-9426", rating: 4.9, reviewCount: 223 },
  { businessName: "Xinh Lounge & Spa", niche: "beauty", city: "Lindale", state: "TX", phone: "(903) 851-5959", rating: 4.8, reviewCount: 118 },
  { businessName: "Tom Murtagh, REALTOR", niche: "real_estate", city: "Twentynine Palms", state: "CA", phone: "(818) 825-0640", rating: 5, reviewCount: 106 },
  { businessName: "Kelly & Company", niche: "beauty", city: "Sheridan", state: "AR", phone: "(870) 942-0902", rating: 4.9, reviewCount: 88 },
  { businessName: "Sonya Jindra-Bringing You The Best In Real Estate", niche: "real_estate", city: "Hamburg", state: "NY", phone: "(716) 787-7653", rating: 5, reviewCount: 76 },
  { businessName: "Relevant Real Estate", niche: "real_estate", city: "Redmond", state: "OR", phone: "(541) 848-0715", rating: 5, reviewCount: 61 },
  { businessName: "Ana's Hair Salon", niche: "beauty", city: "Pine Bluff", state: "AR", phone: "(870) 541-9333", rating: 4.8, reviewCount: 58 },
  { businessName: "Hair X-Perts", niche: "beauty", city: "Effingham", state: "IL", phone: "(217) 342-1084", rating: 4.6, reviewCount: 46 },
  { businessName: "Eclipse Beauty & Barber", niche: "beauty", city: "Charleston", state: "IL", phone: "(217) 348-6700", rating: 4.9, reviewCount: 43 },
  { businessName: "Final Impressions LLC", niche: "concrete", city: "Casper", state: "WY", phone: "(307) 247-2938", rating: 4.4, reviewCount: 20 },
  { businessName: "Rocky Mountain Tree Care Specialists, Inc.", niche: "tree", city: "Great Falls", state: "MT", phone: "", rating: 4.8, reviewCount: 17 },
  { businessName: "2G Hauling & Removal", niche: "junk_removal", city: "", state: "MT", phone: "(406) 871-4691", rating: 5, reviewCount: 3 },
  { businessName: "Septic Tank Services", niche: "septic", city: "Manhattan", state: "MT", phone: "(406) 284-3325", rating: 4, reviewCount: 4 },
  { businessName: "Martin Fencing", niche: "fence", city: "Miles City", state: "MT", phone: "(406) 234-1133", rating: 3.8, reviewCount: 4 },
  { businessName: "Trayer Construction", niche: "septic", city: "", state: "MT", phone: "(406) 649-2418", rating: 5, reviewCount: 4 },
  { businessName: "Larsens Tree Service", niche: "tree", city: "Inkom", state: "ID", phone: "(208) 775-4547", rating: 4, reviewCount: 4 },
  { businessName: "Tom's Flat Roof Repair", niche: "roofing", city: "Hays", state: "KS", phone: "(785) 625-9711", rating: 4, reviewCount: 4 },
  { businessName: "Budget Trimmers Yard Service", niche: "tree", city: "Havre", state: "MT", phone: "(406) 265-1581", rating: 4.7, reviewCount: 3 },
  { businessName: "Callison Drilling", niche: "well_water", city: "Alberton", state: "MT", phone: "(406) 207-1910", rating: 3.7, reviewCount: 3 },
  { businessName: "JP's Water and Sewer Service", niche: "septic", city: "Afton", state: "WY", phone: "(307) 887-9363", rating: 5, reviewCount: 3 },
  { businessName: "Mile Hi Lawn & Tree Care", niche: "tree", city: "Cheyenne", state: "WY", phone: "(307) 635-8472", rating: 3.7, reviewCount: 3 },
  { businessName: "Tip Top Fence and Trees", niche: "fence", city: "Hamilton", state: "MT", phone: "(406) 361-5452", rating: 5, reviewCount: 2 },
  { businessName: "Wagoners Excavation", niche: "excavating", city: "Columbia Falls", state: "MT", phone: "(406) 871-5214", rating: 4.5, reviewCount: 2 },
  { businessName: "A & C Tree & Landscape Services, LLC", niche: "tree", city: "Judsonia", state: "AR", phone: "(501) 207-2609", rating: 4.5, reviewCount: 2 },
  { businessName: "Riverside Plumbing & Heating", niche: "plumbing", city: "Superior", state: "MT", phone: "(406) 240-7586", rating: 5, reviewCount: 1 },
  { businessName: "Corveau Drilling and Construction", niche: "well_water", city: "Great Falls", state: "MT", phone: "(406) 761-1274", rating: 5, reviewCount: 1 },
  { businessName: "BCS Roofing", niche: "roofing", city: "Franklin", state: "TX", phone: "(979) 589-7663", rating: 4.9, reviewCount: 57 },
  { businessName: "Bison Fence LLC", niche: "fence", city: "Great Falls", state: "MT", phone: "(406) 899-8884", rating: 4.6, reviewCount: 22 },
  { businessName: "American Maid", niche: "cleaning", city: "Sheridan", state: "WY", phone: "(307) 672-9851", rating: 3.4, reviewCount: 18 },
  { businessName: "Sanchez and Son Landscaping", niche: "landscaping", city: "Twin Falls", state: "ID", phone: "(208) 613-5232", rating: 4.6, reviewCount: 18 },
  { businessName: "Skyes Landscaping & Services", niche: "landscaping", city: "Pocatello", state: "ID", phone: "(208) 269-0307", rating: 3.8, reviewCount: 17 },
  { businessName: "MOLSL (Missouri Lawn Snow Landscape)", niche: "landscaping", city: "Independence", state: "MO", phone: "(816) 699-3301", rating: 5, reviewCount: 16 },
  { businessName: "Cancholas cleaning service llc", niche: "cleaning", city: "Payette", state: "ID", phone: "(208) 405-3474", rating: 4.7, reviewCount: 15 },
  { businessName: "Jack of Trades", niche: "landscaping", city: "", state: "ID", phone: "(208) 251-0594", rating: 4.9, reviewCount: 15 },
  { businessName: "Pro landscapes", niche: "landscaping", city: "Heber Springs", state: "AR", phone: "(501) 505-6461", rating: 4.8, reviewCount: 15 },
  { businessName: "EZ Junk Removal LLC", niche: "junk_removal", city: "Coeur d'Alene", state: "ID", phone: "(208) 659-9130", rating: 5, reviewCount: 15 },
  { businessName: "Cowboy Lawn and Tree", niche: "landscaping", city: "", state: "ID", phone: "(208) 351-8916", rating: 4.9, reviewCount: 14 },
  { businessName: "Montes Trees and Junk", niche: "junk_removal", city: "", state: "", phone: "(229) 421-5324", rating: 5, reviewCount: 14 },
  { businessName: "Cys Lawn Maintenance", niche: "landscaping", city: "Arnprior", state: "ON", phone: "(613) 794-5923", rating: 4.7, reviewCount: 12 },
  { businessName: "Bust'n Suds", niche: "pressure_wash", city: "Cheyenne", state: "WY", phone: "(307) 414-0976", rating: 4.5, reviewCount: 11 },
  { businessName: "Double E Hauling Junk Removal", niche: "junk_removal", city: "Rock Springs", state: "WY", phone: "(307) 389-3434", rating: 5, reviewCount: 10 },
  { businessName: "Junk B Gone", niche: "junk_removal", city: "Kimberly", state: "ID", phone: "(208) 794-8966", rating: 5, reviewCount: 8 },
  { businessName: "Birchell Well Drilling", niche: "well_water", city: "Big Timber", state: "MT", phone: "(406) 932-5697", rating: 0, reviewCount: 0 },
  { businessName: "Roofguard Roofing Co", niche: "roofing", city: "Plains", state: "KS", phone: "(940) 236-6056", rating: 0, reviewCount: 0 },
  { businessName: "Me Daza Salon", niche: "beauty", city: "La Grande", state: "OR", phone: "(541) 805-5636", rating: 5, reviewCount: 56 },
  { businessName: "Hair Hype Salon", niche: "beauty", city: "Arkadelphia", state: "AR", phone: "(870) 246-2992", rating: 4.6, reviewCount: 54 },
  { businessName: "JB Construction", niche: "construction", city: "Clifton", state: "ID", phone: "(801) 367-0765", rating: 5, reviewCount: 49 },
  { businessName: "Hair Nest /Styles by Paula", niche: "beauty", city: "Moweaqua", state: "IL", phone: "(217) 972-9348", rating: 4.9, reviewCount: 48 },
  { businessName: "Robins Hair Salon", niche: "beauty", city: "Charleston", state: "IL", phone: "(217) 348-1138", rating: 4.9, reviewCount: 48 },
  { businessName: "The Insurance Store", niche: "insurance", city: "Belen", state: "NM", phone: "(505) 861-8283", rating: 4.5, reviewCount: 46 },
  { businessName: "Kut Loose Salon", niche: "beauty", city: "Shelbyville", state: "IL", phone: "(217) 259-4579", rating: 4.9, reviewCount: 42 },
  { businessName: "New Horizons Exteriors", niche: "construction", city: "White", state: "SD", phone: "(605) 690-4797", rating: 5, reviewCount: 42 },
  { businessName: "Steve's Comfort Systems", niche: "hvac", city: "Vermillion", state: "SD", phone: "(605) 624-4557", rating: 4.6, reviewCount: 38 },
  { businessName: "Fuemmeler Tax & Accounting", niche: "accounting", city: "Moberly", state: "MO", phone: "(660) 263-4346", rating: 4.9, reviewCount: 38 },
  { businessName: "Amanda's Villa Inc", niche: "landscaping", city: "White Hall", state: "AR", phone: "(870) 489-5463", rating: 4.8, reviewCount: 35 },
  { businessName: "ON-TRACK Land Clearing & Dirt Work", niche: "excavating", city: "Caledonia", state: "MS", phone: "(662) 251-6880", rating: 4.9, reviewCount: 31 },
  { businessName: "Insurance Corporation of Belize & Nationwide Cash Express Belmopan Branch", niche: "insurance", city: "", state: "", phone: "(501) 822-0473", rating: 4.2, reviewCount: 20 },
  { businessName: "A Cut Above", niche: "beauty", city: "Fordyce", state: "AR", phone: "(870) 352-2477", rating: 4.9, reviewCount: 20 },
  { businessName: "HomeTown Roofing and Construction", niche: "roofing", city: "Pampa", state: "TX", phone: "", rating: 4.9, reviewCount: 14 },
  { businessName: "Pinnacle Solutions LLC", niche: "roofing", city: "Rock Springs", state: "WY", phone: "", rating: 3.3, reviewCount: 12 },
  { businessName: "307 Exterior Revive llc", niche: "pressure_wash", city: "", state: "WY", phone: "(307) 797-9274", rating: 5, reviewCount: 4 },
  { businessName: "Willy's Landscaping Corp.", niche: "landscaping", city: "", state: "", phone: "(787) 385-2545", rating: 3.3, reviewCount: 4 },
  { businessName: "Pressure Point Power Washing", niche: "pressure_wash", city: "", state: "MT", phone: "(406) 270-9134", rating: 5, reviewCount: 3 },
  { businessName: "Advanced Landscapinng", niche: "landscaping", city: "Starkville", state: "MS", phone: "(662) 338-5296", rating: 5, reviewCount: 3 },
  { businessName: "Shaw's Landscaping", niche: "landscaping", city: "Quitman", state: "AR", phone: "(501) 825-8667", rating: 5, reviewCount: 1 },
  { businessName: "Central Lakes Landscape", niche: "landscaping", city: "Grey Eagle", state: "MN", phone: "(320) 285-5715", rating: 5, reviewCount: 1 },
  { businessName: "Great Southern Landscape Co", niche: "landscaping", city: "Columbus", state: "MS", phone: "(662) 329-9167", rating: 3, reviewCount: 1 },
  { businessName: "H&C Landscaping", niche: "landscaping", city: "Sainte-Anne", state: "NB", phone: "(506) 543-2495", rating: 5, reviewCount: 1 },
  { businessName: "Independent Drilling", niche: "well_water", city: "Blackfoot", state: "ID", phone: "(208) 684-3788", rating: 4.3, reviewCount: 32 },
  { businessName: "Triple J Well & Pump Service", niche: "well_water", city: "Kalispell", state: "MT", phone: "(406) 890-2057", rating: 5, reviewCount: 32 },
  { businessName: "Bahamas Air Care Refrigeration & Air Conditioning", niche: "hvac", city: "", state: "", phone: "(242) 810-5060", rating: 4.9, reviewCount: 31 },
  { businessName: "R & D Heating and Air - HVAC Maintenance Contractor, Heating and Air Conditioning Service Pell City AL", niche: "hvac", city: "Pell City", state: "AL", phone: "(205) 999-5877", rating: 5, reviewCount: 23 },
  { businessName: "Roto-Rooter of Ravalli", niche: "plumbing", city: "Hamilton", state: "MT", phone: "(406) 363-2787", rating: 5, reviewCount: 21 },
  { businessName: "Crystal Insurance Brokers", niche: "insurance", city: "Crystal City", state: "MB", phone: "(204) 873-2499", rating: 4.7, reviewCount: 17 },
  { businessName: "Styles For You", niche: "beauty", city: "Marathon", state: "ON", phone: "(807) 229-0661", rating: 4.4, reviewCount: 11 },
  { businessName: "The Beauty Shop", niche: "beauty", city: "Camden", state: "AR", phone: "(870) 413-9484", rating: 4.8, reviewCount: 11 },
  { businessName: "Valley Insurance Associates: Sanchez Agency", niche: "insurance", city: "Alamosa", state: "CO", phone: "(719) 589-6116", rating: 3.3, reviewCount: 10 },
  { businessName: "Eclips Hair Design", niche: "beauty", city: "Kakabeka Falls", state: "ON", phone: "(807) 473-4322", rating: 5, reviewCount: 9 },
  { businessName: "N.A. Puckalo Trucking", niche: "trucking_auto", city: "Iroquois Falls", state: "ON", phone: "(705) 232-4330", rating: 4.2, reviewCount: 5 },
  { businessName: "Down-N-Dirty Cleaning Services", niche: "cleaning", city: "Billings", state: "MT", phone: "", rating: 4.8, reviewCount: 17 },
  { businessName: "Arbor Solutions", niche: "tree", city: "Cheyenne", state: "WY", phone: "(307) 634-5319", rating: 3.7, reviewCount: 9 },
  { businessName: "Hi-Line Drilling Inc", niche: "well_water", city: "Havre", state: "MT", phone: "(406) 265-4210", rating: 5, reviewCount: 8 },
  { businessName: "Mayes Drilling Inc", niche: "well_water", city: "", state: "MT", phone: "(406) 373-5707", rating: 4.4, reviewCount: 7 },
  { businessName: "American Technical Tree Service L.L.C.", niche: "tree", city: "Twin Falls", state: "ID", phone: "(208) 420-2488", rating: 5, reviewCount: 6 },
  { businessName: "Mood Studio", niche: "beauty", city: "Centerville", state: "IA", phone: "(641) 895-7440", rating: 5, reviewCount: 3 },
  { businessName: "Absolute Comfort LLC", niche: "hvac", city: "Scott City", state: "KS", phone: "(620) 874-0405", rating: 5, reviewCount: 2 },
  { businessName: "Southwest Kansas Roofing", niche: "roofing", city: "Garden City", state: "KS", phone: "(620) 266-5060", rating: 0, reviewCount: 0 },
  { businessName: "Zepeda Seguros", niche: "insurance", city: "", state: "", phone: "", rating: 4.9, reviewCount: 83 },
  { businessName: "Tinsley's Moving LLC", niche: "junk_removal", city: "", state: "MT", phone: "(406) 590-1307", rating: 4.7, reviewCount: 62 },
  { businessName: "Midtown plowing & landscaping", niche: "landscaping", city: "Tomahawk", state: "WI", phone: "(715) 612-2626", rating: 5, reviewCount: 3 },
  { businessName: "ABC HEAT AND AIR CONDITIONING HVAC LLC", niche: "hvac", city: "Cape Girardeau", state: "MO", phone: "(573) 450-1472", rating: 4.9, reviewCount: 155 },
  { businessName: "DL Roofing & Construction", niche: "roofing", city: "Sioux City", state: "IA", phone: "(712) 577-4217", rating: 4.9, reviewCount: 154 },
  { businessName: "H & L Drilling", niche: "well_water", city: "East Helena", state: "MT", phone: "(406) 227-7435", rating: 4.7, reviewCount: 40 },
  { businessName: "Housley Pumps Sales & Services", niche: "well_water", city: "St Anthony", state: "ID", phone: "(208) 624-3772", rating: 4.4, reviewCount: 36 },
  { businessName: "Matt's Plumbing Service LLC", niche: "septic", city: "Dubois", state: "WY", phone: "(307) 450-8587", rating: 5, reviewCount: 35 },
  { businessName: "Air conditioners Rental since 1978 in Canada", niche: "hvac", city: "Montréal", state: "QC", phone: "(514) 931-3571", rating: 4.4, reviewCount: 34 },
  { businessName: "H & H Heating and Air", niche: "hvac", city: "Paducah", state: "KY", phone: "(270) 210-1619", rating: 5, reviewCount: 34 },
  { businessName: "Split Ends", niche: "beauty", city: "Mt Zion", state: "IL", phone: "(217) 864-2688", rating: 5, reviewCount: 19 },
  { businessName: "Ella's Salon and Boutique", niche: "beauty", city: "Camden", state: "AR", phone: "(870) 836-0006", rating: 4.9, reviewCount: 19 },
  { businessName: "Kimberley Guay-Dubois Courtière immobilière Résidentielle", niche: "real_estate", city: "Albanel", state: "QC", phone: "(418) 618-5031", rating: 5, reviewCount: 19 },
  { businessName: "Insurance Corporation of Belize & Nationwide Cash Express", niche: "insurance", city: "", state: "", phone: "(501) 523-2516", rating: 4.1, reviewCount: 18 },
  { businessName: "Shear Talent", niche: "beauty", city: "Manitouwadge", state: "ON", phone: "(807) 826-3548", rating: 4.3, reviewCount: 18 },
  { businessName: "RF&G Insurance (SPL)", niche: "insurance", city: "", state: "", phone: "(501) 823-0167", rating: 4.6, reviewCount: 17 },
  { businessName: "Retro Society Salon + Hair Extensions", niche: "beauty", city: "Arkadelphia", state: "AR", phone: "(870) 210-0996", rating: 4.8, reviewCount: 17 },
  { businessName: "Gazon Larouche", niche: "landscaping", city: "La Baie", state: "QC", phone: "(418) 677-2657", rating: 4.7, reviewCount: 15 },
  { businessName: "Hair By Donna", niche: "beauty", city: "Bearden", state: "AR", phone: "(870) 687-3636", rating: 4.9, reviewCount: 12 },
  { businessName: "Faye Spa", niche: "beauty", city: "Lafayette", state: "IN", phone: "(765) 767-1234", rating: 5, reviewCount: 12 },
  { businessName: "Kristi Veitz", niche: "insurance", city: "Grand Forks", state: "ND", phone: "(701) 775-3132", rating: 5, reviewCount: 10 },
  { businessName: "Grass Flex Guys", niche: "landscaping", city: "Columbus", state: "MS", phone: "(662) 400-5948", rating: 4.2, reviewCount: 5 },
  { businessName: "Legault Landscaping", niche: "landscaping", city: "Timmins", state: "ON", phone: "(705) 266-5243", rating: 0, reviewCount: 0 },
  { businessName: "Powerhouse Air Conditioning", niche: "hvac", city: "Summerland Key", state: "FL", phone: "(305) 394-5448", rating: 4.8, reviewCount: 18 },
  { businessName: "BranchesBeGone", niche: "tree", city: "", state: "ID", phone: "(208) 530-6333", rating: 5, reviewCount: 15 },
  { businessName: "M&H Septic Pumping and Porta Potties", niche: "septic", city: "Troy", state: "MT", phone: "(406) 295-9570", rating: 5, reviewCount: 13 },
  { businessName: "Nania, Inc", niche: "excavating", city: "Mills", state: "WY", phone: "(307) 472-5755", rating: 4.4, reviewCount: 9 },
  { businessName: "Terry’s HVAC", niche: "hvac", city: "Tillar", state: "AR", phone: "(870) 538-5202", rating: 5, reviewCount: 9 },
  { businessName: "Foothill Construction Services", niche: "excavating", city: "Kalispell", state: "MT", phone: "(406) 210-0506", rating: 5, reviewCount: 9 },
  { businessName: "Higgins Drilling Co", niche: "well_water", city: "Miles City", state: "MT", phone: "(406) 232-2565", rating: 5, reviewCount: 8 },
  { businessName: "Main Harbor Pumps & Well Drill", niche: "well_water", city: "Ronan", state: "MT", phone: "(406) 675-3179", rating: 4.6, reviewCount: 8 },
  { businessName: "Eckhardt Workx LLC", niche: "fence", city: "", state: "ID", phone: "(208) 739-5098", rating: 5, reviewCount: 8 },
  { businessName: "Triple T Septic Cleaning", niche: "septic", city: "Montpelier", state: "ID", phone: "(208) 847-3265", rating: 4.4, reviewCount: 7 },
  { businessName: "Gestrin Well Drilling", niche: "well_water", city: "Donnelly", state: "ID", phone: "(208) 325-8637", rating: 5, reviewCount: 7 },
  { businessName: "Independent Drilling Ashton", niche: "well_water", city: "Ashton", state: "ID", phone: "(208) 652-3799", rating: 5, reviewCount: 7 },
  { businessName: "Guiding Light Electric, Inc.", niche: "electrical", city: "", state: "", phone: "(816) 361-5150", rating: 5, reviewCount: 7 },
  { businessName: "Babbitt Well Pumps & Service", niche: "well_water", city: "Missoula", state: "MT", phone: "(406) 531-3585", rating: 5, reviewCount: 7 },
  { businessName: "A Cut Above Tree Service and Land Management", niche: "tree", city: "Plains", state: "MT", phone: "(406) 304-4937", rating: 5, reviewCount: 6 },
  { businessName: "Rock Solid Excavating Inc", niche: "septic", city: "Park City", state: "MT", phone: "(406) 855-8371", rating: 4.3, reviewCount: 6 },
  { businessName: "Sheridan Sewer & Drain", niche: "plumbing", city: "", state: "WY", phone: "(307) 429-8474", rating: 4, reviewCount: 6 },
  { businessName: "JP Heating & Cooling", niche: "hvac", city: "Sault Ste. Marie", state: "ON", phone: "(705) 206-9030", rating: 5, reviewCount: 6 },
  { businessName: "DV Douglass Roofing", niche: "roofing", city: "Garden City", state: "KS", phone: "(620) 276-7474", rating: 5, reviewCount: 6 },
  { businessName: "Steel Top Roofing & Construction", niche: "roofing", city: "Wichita Falls", state: "TX", phone: "(940) 249-3714", rating: 4.8, reviewCount: 6 },
  { businessName: "Blue Ribbon Tree Service", niche: "tree", city: "Powell", state: "WY", phone: "(307) 272-2801", rating: 5, reviewCount: 5 },
  { businessName: "Bishop Well Drilling Inc", niche: "well_water", city: "Buhl", state: "ID", phone: "(208) 308-1982", rating: 4.2, reviewCount: 5 },
  { businessName: "Sorlie Excavating Inc.", niche: "excavating", city: "Thompson Falls", state: "MT", phone: "(406) 827-4495", rating: 5, reviewCount: 5 },
  { businessName: "Action Septic Pumping", niche: "septic", city: "Bigfork", state: "MT", phone: "(406) 837-4714", rating: 5, reviewCount: 5 },
  { businessName: "Darland's Skid Steer Services", niche: "septic", city: "Arco", state: "ID", phone: "(208) 720-7532", rating: 4.2, reviewCount: 5 },
  { businessName: "Phoenix Fence", niche: "fence", city: "Filer", state: "ID", phone: "(208) 316-7272", rating: 5, reviewCount: 5 },
  { businessName: "Allstate Well Drilling", niche: "well_water", city: "Horseshoe Bend", state: "ID", phone: "(208) 462-4621", rating: 4.2, reviewCount: 5 },
  { businessName: "Range Brothers Roofing", niche: "roofing", city: "Arnett", state: "OK", phone: "(580) 885-7323", rating: 5, reviewCount: 5 },
  { businessName: "Top Notch Tree Works LLC", niche: "tree", city: "Kalispell", state: "MT", phone: "(208) 935-5782", rating: 5, reviewCount: 5 },
  { businessName: "Rocky Mountain Remodels LLC", niche: "construction", city: "", state: "WY", phone: "(307) 352-9509", rating: 5, reviewCount: 4 },
  { businessName: "Smith Septic Pumping", niche: "septic", city: "Polson", state: "MT", phone: "(406) 883-6708", rating: 5, reviewCount: 3 },
  { businessName: "LynnAnn's Path to Nature, Gardening with Conscience", niche: "landscaping", city: "Rhinelander", state: "WI", phone: "(715) 272-2032", rating: 5, reviewCount: 3 },
  { businessName: "HOME PROTECTOR INSURANCE, Benque Viejo", niche: "insurance", city: "", state: "", phone: "(501) 600-3872", rating: 4.7, reviewCount: 3 },
  { businessName: "Louella's Garden Design LLC", niche: "landscaping", city: "Quitman", state: "AR", phone: "(501) 306-9462", rating: 5, reviewCount: 1 },
  { businessName: "GNP Seguros Supervisoría Oaxaca", niche: "insurance", city: "", state: "", phone: "", rating: 3.7, reviewCount: 54 },
  { businessName: "Beast Mode Moving LLC", niche: "junk_removal", city: "", state: "MT", phone: "(406) 491-0506", rating: 4.5, reviewCount: 41 },
  { businessName: "Centro de Atención MetLife La Cascada", niche: "insurance", city: "", state: "", phone: "", rating: 4.7, reviewCount: 29 },
  { businessName: "Wyo Lawn & Tree", niche: "tree", city: "Douglas", state: "WY", phone: "(307) 358-0595", rating: 4.3, reviewCount: 4 },
  { businessName: "Kevin's Heating", niche: "hvac", city: "", state: "", phone: "(705) 852-0583", rating: 4.8, reviewCount: 4 },
  { businessName: "Timberline Services Inc", niche: "septic", city: "Sundance", state: "WY", phone: "(307) 283-2818", rating: 5, reviewCount: 3 },
  { businessName: "Broadus Tree Service L.L.C.", niche: "tree", city: "Broadus", state: "MT", phone: "(406) 436-2716", rating: 5, reviewCount: 1 },
  { businessName: "High Country Tree Services", niche: "tree", city: "Butte", state: "MT", phone: "(406) 533-8829", rating: 5, reviewCount: 1 },
  { businessName: "Western Waste Solutions Inc", niche: "junk_removal", city: "Rozet", state: "WY", phone: "(307) 685-2556", rating: 2, reviewCount: 12 },
  { businessName: "Avenidad Bugambilia", niche: "retail", city: "", state: "", phone: "", rating: 4.5, reviewCount: 6 },
  { businessName: "Guardia Nacional 535 CIA", niche: "retail", city: "", state: "", phone: "", rating: 5, reviewCount: 6 },
  { businessName: "Signature Salon", niche: "beauty", city: "Decatur", state: "IL", phone: "(217) 864-5641", rating: 4.2, reviewCount: 73 },
  { businessName: "Fortress Fence", niche: "fence", city: "Pinehurst", state: "ID", phone: "(208) 784-3798", rating: 4.8, reviewCount: 19 },
  { businessName: "B & B Sani Service", niche: "septic", city: "Hayden", state: "ID", phone: "(208) 772-3566", rating: 4.3, reviewCount: 18 },
  { businessName: "A-1 Drilling", niche: "well_water", city: "Laurel", state: "MT", phone: "(406) 628-6364", rating: 3.6, reviewCount: 17 },
  { businessName: "Teton Water Works", niche: "well_water", city: "Shelley", state: "ID", phone: "(208) 357-1850", rating: 4.1, reviewCount: 16 },
  { businessName: "Bechtel Tree Service", niche: "tree", city: "Simms", state: "MT", phone: "(406) 468-5203", rating: 4.8, reviewCount: 14 },
  { businessName: "Arrow Septic & Drain", niche: "plumbing", city: "Lewistown", state: "MT", phone: "(406) 350-0737", rating: 4.1, reviewCount: 14 },
  { businessName: "Coats Rooter Service", niche: "septic", city: "Weston", state: "ID", phone: "(208) 747-3928", rating: 4.3, reviewCount: 13 },
  { businessName: "Standard Plumbing Supply", niche: "plumbing", city: "Hailey", state: "ID", phone: "(208) 578-1740", rating: 4.9, reviewCount: 10 },
  { businessName: "Normandin Heating & AC Inc", niche: "hvac", city: "Damar", state: "KS", phone: "(785) 839-4444", rating: 5, reviewCount: 9 },
  { businessName: "Reid's Hvac Repair Services ( air conditioning and Refrigeration ), solar systems services and hybrid vehicle diagnostics", niche: "hvac", city: "", state: "", phone: "(876) 835-6196", rating: 5, reviewCount: 9 },
  { businessName: "Workhorse fencing", niche: "fence", city: "Rock Springs", state: "WY", phone: "(307) 274-6297", rating: 5, reviewCount: 8 },
  { businessName: "Fire Line Welding LLC", niche: "fence", city: "Evansville", state: "WY", phone: "(307) 797-1098", rating: 4.5, reviewCount: 8 },
  { businessName: "All Over Heating And Cooling, Llc", niche: "hvac", city: "Atwood", state: "KS", phone: "(785) 202-2086", rating: 4.9, reviewCount: 8 },
  { businessName: "Rhinelander Heating & Air Conditioning", niche: "hvac", city: "Rhinelander", state: "WI", phone: "(715) 979-8228", rating: 4.5, reviewCount: 8 },
  { businessName: "SR&C Steve's Roofing services & Chimney clean service Ltd", niche: "roofing", city: "Sioux City", state: "IA", phone: "(712) 317-8543", rating: 4.1, reviewCount: 8 },
  { businessName: "Bull Mountain Fencing and Supply", niche: "fence", city: "Roundup", state: "MT", phone: "(406) 323-8006", rating: 5, reviewCount: 7 },
  { businessName: "Jim's Well Drilling", niche: "well_water", city: "Kuna", state: "ID", phone: "(208) 634-0011", rating: 5, reviewCount: 7 },
  { businessName: "MKE Mechanical", niche: "septic", city: "Laramie", state: "WY", phone: "(307) 761-1929", rating: 3.9, reviewCount: 7 },
  { businessName: "Kiwi Petes Tree Services", niche: "tree", city: "Miles City", state: "MT", phone: "(406) 232-7029", rating: 5, reviewCount: 6 },
  { businessName: "AAA Trees On the Move", niche: "tree", city: "Joliet", state: "MT", phone: "(406) 628-1344", rating: 4, reviewCount: 6 },
  { businessName: "Hoyt Septic & Excavation", niche: "excavating", city: "Rupert", state: "ID", phone: "(208) 431-4698", rating: 5, reviewCount: 6 },
  { businessName: "Beartooth Fencing LLC", niche: "fence", city: "Reed Point", state: "MT", phone: "(406) 425-0332", rating: 4.3, reviewCount: 6 },
  { businessName: "Ward's Well Services Inc", niche: "well_water", city: "Riverton", state: "WY", phone: "(307) 856-9014", rating: 4.8, reviewCount: 6 },
  { businessName: "Everett's Heating Ltd", niche: "hvac", city: "Aroostook", state: "NB", phone: "(506) 273-2431", rating: 4.3, reviewCount: 6 },
  { businessName: "Deno's Excavating Services", niche: "excavating", city: "Rupert", state: "ID", phone: "(208) 436-6526", rating: 4.4, reviewCount: 5 },
  { businessName: "Joe's Tree Service", niche: "tree", city: "Huntley", state: "MT", phone: "(406) 263-7208", rating: 3.6, reviewCount: 5 },
  { businessName: "Lou's Drilling", niche: "well_water", city: "Riverton", state: "WY", phone: "(307) 857-3064", rating: 4.6, reviewCount: 5 },
  { businessName: "Forest Land Solutions LLC", niche: "tree", city: "Arco", state: "ID", phone: "(208) 831-7074", rating: 5, reviewCount: 5 },
  { businessName: "Christian Heating And Air", niche: "hvac", city: "Metropolis", state: "IL", phone: "(618) 638-4040", rating: 3.8, reviewCount: 5 },
  { businessName: "TXB Roofing & Construction", niche: "roofing", city: "Burkburnett", state: "TX", phone: "(940) 283-5221", rating: 5, reviewCount: 5 },
  { businessName: "Boyd Conzemius Agency Inc American Family Insurance", niche: "insurance", city: "Pierre", state: "SD", phone: "(605) 224-6271", rating: 3, reviewCount: 2 },
  { businessName: "Deneigement honfleur", niche: "snow_removal", city: "Sainte-Monique", state: "QC", phone: "(418) 720-2290", rating: 5, reviewCount: 1 },
  { businessName: "Maikel Cueto Peluquería", niche: "beauty", city: "", state: "", phone: "(535) 418-6438", rating: 5, reviewCount: 1 },
  { businessName: "Unique Lawn and Landscaping LLC", niche: "landscaping", city: "Lakewood", state: "CO", phone: "(720) 723-9465", rating: 5, reviewCount: 60 },
  { businessName: "Rueve Landscape Company", niche: "landscaping", city: "Cincinnati", state: "OH", phone: "(513) 598-5436", rating: 4.9, reviewCount: 55 },
  { businessName: "Three Peaks Maintenance LLC.", niche: "pressure_wash", city: "Kimberly", state: "ID", phone: "(208) 644-0589", rating: 5, reviewCount: 45 },
  { businessName: "406 Moving & More", niche: "junk_removal", city: "", state: "MT", phone: "(406) 459-8534", rating: 5, reviewCount: 37 },
  { businessName: "Custom Landscaping", niche: "landscaping", city: "Eagle River", state: "WI", phone: "(715) 479-6762", rating: 4, reviewCount: 25 },
  { businessName: "Coyote Sanitation", niche: "junk_removal", city: "Burns", state: "WY", phone: "(307) 547-3654", rating: 3.9, reviewCount: 24 },
  { businessName: "Valley Tree Service LLC", niche: "tree", city: "Hardin", state: "MT", phone: "(406) 679-1969", rating: 5, reviewCount: 4 },
  { businessName: "B & B Septic Services Inc", niche: "plumbing", city: "Baker", state: "MT", phone: "(406) 778-2599", rating: 4.5, reviewCount: 4 },
  { businessName: "May Excavation, LLC", niche: "septic", city: "Troy", state: "MT", phone: "(406) 295-7540", rating: 5, reviewCount: 4 },
  { businessName: "Titan Inc", niche: "excavating", city: "Ennis", state: "MT", phone: "(406) 682-7714", rating: 5, reviewCount: 4 },
  { businessName: "Andre Excavation & Sewer Service", niche: "excavating", city: "", state: "MT", phone: "(406) 727-0032", rating: 5, reviewCount: 4 },
  { businessName: "Cheyenne Fence Company", niche: "fence", city: "", state: "WY", phone: "(307) 242-6539", rating: 3, reviewCount: 4 },
  { businessName: "Riverbound Excavation", niche: "excavating", city: "Cascade", state: "ID", phone: "(208) 954-6831", rating: 5, reviewCount: 4 },
  { businessName: "Kew A/c, Refrigeration & Plumbing Services", niche: "plumbing", city: "", state: "", phone: "(876) 414-3256", rating: 5, reviewCount: 4 },
  { businessName: "Mr AC - Modern Refrigeration and Air Conditioning (Sales & Service)", niche: "hvac", city: "", state: "", phone: "(876) 955-3237", rating: 4.3, reviewCount: 4 },
  { businessName: "Comfort Heating & Air Conditioning", niche: "hvac", city: "New Liskeard", state: "ON", phone: "(705) 647-8359", rating: 4, reviewCount: 4 },
  { businessName: "Harmony Heating & Cooling Services", niche: "hvac", city: "Hancock", state: "MI", phone: "(906) 332-2536", rating: 5, reviewCount: 4 },
  { businessName: "Alan's Pump Sales & Services", niche: "well_water", city: "Kalispell", state: "MT", phone: "(406) 756-7728", rating: 5, reviewCount: 4 },
  { businessName: "Twin Lakes Dirt Works", niche: "excavating", city: "Frenchtown", state: "MT", phone: "(406) 240-1445", rating: 5, reviewCount: 3 },
  { businessName: "Sublette Pump Services", niche: "well_water", city: "Pinedale", state: "WY", phone: "(307) 413-1398", rating: 5, reviewCount: 3 },
  { businessName: "Lake ARC LLC", niche: "fence", city: "", state: "WY", phone: "(307) 371-5981", rating: 5, reviewCount: 3 },
  { businessName: "DJ's Septic", niche: "plumbing", city: "Darby", state: "MT", phone: "(406) 274-0115", rating: 5, reviewCount: 3 },
  { businessName: "Montana Custom Fence", niche: "fence", city: "Hamilton", state: "MT", phone: "(701) 690-7436", rating: 5, reviewCount: 3 },
  { businessName: "Advance Fence", niche: "fence", city: "Sheridan", state: "WY", phone: "(307) 673-9200", rating: 3.7, reviewCount: 3 },
  { businessName: "Carl Pitts & Sons Well Drilling & Pump Service LLC", niche: "well_water", city: "Oldtown", state: "ID", phone: "(208) 437-4168", rating: 4, reviewCount: 3 },
  { businessName: "Ace Fence Company", niche: "fence", city: "Post Falls", state: "ID", phone: "(208) 446-4141", rating: 5, reviewCount: 3 },
  { businessName: "Travis Frandsen Drilling", niche: "well_water", city: "Rexburg", state: "ID", phone: "(208) 317-5584", rating: 5, reviewCount: 3 },
  { businessName: "Wiebe's roofing & construction LLC", niche: "roofing", city: "Satanta", state: "KS", phone: "(620) 640-7830", rating: 5, reviewCount: 3 },
  { businessName: "Aqua Shield Roofing & Construction", niche: "roofing", city: "Garden City", state: "KS", phone: "(620) 428-6744", rating: 5, reviewCount: 3 },
  { businessName: "SDK Custom Fencing", niche: "fence", city: "Billings", state: "MT", phone: "(406) 839-7828", rating: 5, reviewCount: 3 },
  { businessName: "Timberline Fencing", niche: "fence", city: "Butte", state: "MT", phone: "(406) 494-4996", rating: 3.3, reviewCount: 3 },
  { businessName: "Rock Creek Drilling Inc", niche: "well_water", city: "Cheyenne", state: "WY", phone: "(307) 632-5510", rating: 5, reviewCount: 3 },
  { businessName: "Gillette Fence Company", niche: "fence", city: "Gillette", state: "WY", phone: "(307) 299-8777", rating: 4.7, reviewCount: 3 },
  { businessName: "Central Drilling", niche: "well_water", city: "Lewistown", state: "MT", phone: "(406) 538-7355", rating: 1.5, reviewCount: 2 },
  { businessName: "Best Septic", niche: "septic", city: "Heron", state: "MT", phone: "(406) 499-9969", rating: 5, reviewCount: 2 },
  { businessName: "Fencing Montana", niche: "fence", city: "Manhattan", state: "MT", phone: "(406) 261-8804", rating: 5, reviewCount: 2 },
  { businessName: "Verlin's Pump Services", niche: "well_water", city: "Lava Hot Springs", state: "ID", phone: "(208) 251-5581", rating: 5, reviewCount: 2 },
  { businessName: "Simoneau Excavation", niche: "excavating", city: "Sainte-Luce", state: "QC", phone: "(581) 624-1700", rating: 3, reviewCount: 2 },
  { businessName: "C&H Cooling and Heating Inc.", niche: "hvac", city: "Bainbridge", state: "NY", phone: "(607) 316-4178", rating: 5, reviewCount: 2 },
  { businessName: "Sir Cool Air Conditioning installation: Air Conditioner Repair Company Jamaica", niche: "hvac", city: "", state: "", phone: "(876) 852-1506", rating: 3, reviewCount: 2 },
  { businessName: "Al's Refrigeration Heating & Air Conditioning", niche: "hvac", city: "", state: "", phone: "(705) 266-5756", rating: 5, reviewCount: 2 },
  { businessName: "Blass Roofing", niche: "roofing", city: "New Cordell", state: "OK", phone: "(580) 832-0253", rating: 5, reviewCount: 2 },
  { businessName: "Boyce Construction", niche: "fence", city: "Havre", state: "MT", phone: "(406) 945-3901", rating: 5, reviewCount: 1 },
  { businessName: "Tree service & Handyman", niche: "tree", city: "Great Falls", state: "MT", phone: "(406) 590-6897", rating: 5, reviewCount: 1 },
  { businessName: "Reparto La Victoria.Carretera de Patria#3Alto", niche: "retail", city: "", state: "", phone: "(535) 313-3327", rating: 0, reviewCount: 0 },
  { businessName: "Freestyle Landscaping Inc.", niche: "landscaping", city: "Bélair", state: "MB", phone: "(204) 754-7208", rating: 4.9, reviewCount: 19 },
  { businessName: "Seguros Serfin S", niche: "insurance", city: "", state: "", phone: "", rating: 5, reviewCount: 13 },
  { businessName: "OC MultiSeguros Papantla", niche: "insurance", city: "", state: "", phone: "", rating: 4.6, reviewCount: 11 },
  { businessName: "Grass Gurus", niche: "landscaping", city: "", state: "MT", phone: "(406) 310-6103", rating: 4.1, reviewCount: 9 },
  { businessName: "Bighorn Pressure Wash", niche: "pressure_wash", city: "", state: "WY", phone: "(307) 250-8860", rating: 5, reviewCount: 9 },
  { businessName: "Montana Wash LLC", niche: "pressure_wash", city: "", state: "MT", phone: "(406) 565-9283", rating: 5, reviewCount: 8 },
  { businessName: "Bootstrap Hauling LLC", niche: "junk_removal", city: "", state: "WY", phone: "(307) 314-2084", rating: 5, reviewCount: 8 },
  { businessName: "Tu especialista en seguros", niche: "insurance", city: "", state: "", phone: "", rating: 5, reviewCount: 8 },
  { businessName: "Thompson Lawn Service", niche: "landscaping", city: "Starkville", state: "MS", phone: "(662) 722-8370", rating: 5, reviewCount: 8 },
  { businessName: "Gonzalez Lawn Care Services", niche: "pressure_wash", city: "Jerome", state: "ID", phone: "(208) 539-5032", rating: 5, reviewCount: 7 },
  { businessName: "Alpine Landscaping Northwoods LLC", niche: "landscaping", city: "Rhinelander", state: "WI", phone: "(715) 490-1103", rating: 4.3, reviewCount: 6 },
  { businessName: "WYCO Waste Services LLC", niche: "junk_removal", city: "Dubois", state: "WY", phone: "(307) 450-3217", rating: 4.2, reviewCount: 5 },
  { businessName: "Yard Works Design", niche: "landscaping", city: "Denver", state: "CO", phone: "(720) 381-0858", rating: 5, reviewCount: 5 },
  { businessName: "Under Pressure Power Washing, LLC", niche: "cleaning", city: "Great Falls", state: "MT", phone: "(406) 781-6734", rating: 3.6, reviewCount: 5 },
  { businessName: "Next Level Insurance", niche: "insurance", city: "Salt Lake City", state: "UT", phone: "(385) 289-0808", rating: 4.8, reviewCount: 441 },
  { businessName: "Inszone Insurance Services", niche: "insurance", city: "Thousand Oaks", state: "CA", phone: "(805) 496-1424", rating: 4.9, reviewCount: 193 },
  { businessName: "Sea Level Spa and Salon", niche: "beauty", city: "Marathon", state: "FL", phone: "(305) 916-0919", rating: 4.8, reviewCount: 166 },
  { businessName: "Mountain View Insurance Agency, Inc.", niche: "insurance", city: "El Paso", state: "TX", phone: "(915) 855-2599", rating: 4.8, reviewCount: 98 },
  { businessName: "Salon 620", niche: "beauty", city: "Arkadelphia", state: "AR", phone: "(870) 246-6292", rating: 4.6, reviewCount: 95 },
  { businessName: "Aire Care", niche: "hvac", city: "Houghton", state: "MI", phone: "(906) 482-3500", rating: 4.4, reviewCount: 75 },
  { businessName: "Jardin d'Or", niche: "landscaping", city: "Saint-Félicien", state: "QC", phone: "(418) 679-3593", rating: 4.9, reviewCount: 42 },
  { businessName: "Carolina Insurance Agency", niche: "insurance", city: "Youngsville", state: "NC", phone: "(919) 556-5682", rating: 4.8, reviewCount: 41 },
  { businessName: "Insurance Corporation of Belize & Nationwide Cash Express Benque Viejo Branch", niche: "insurance", city: "", state: "", phone: "(501) 823-2319", rating: 4, reviewCount: 41 },
  { businessName: "People's Insurance Inc", niche: "insurance", city: "Leitchfield", state: "KY", phone: "(270) 259-3711", rating: 4, reviewCount: 35 },
  { businessName: "Maletta's Hair Care", niche: "beauty", city: "Thunder Bay", state: "ON", phone: "(807) 344-1116", rating: 4.7, reviewCount: 33 },
  { businessName: "The Amanda Wilson Team - ERA Martin and Associates", niche: "real_estate", city: "Gallipolis", state: "OH", phone: "(937) 607-0628", rating: 5, reviewCount: 27 },
  { businessName: "Hayes Insurance Group", niche: "insurance", city: "Eugene", state: "OR", phone: "(541) 762-8000", rating: 4.8, reviewCount: 23 },
  { businessName: "Alamosa Insurance Agency", niche: "insurance", city: "Alamosa", state: "CO", phone: "(719) 349-5498", rating: 4.6, reviewCount: 21 },
  { businessName: "Cindy Sellstrom Real Estate Agent", niche: "real_estate", city: "Jamestown", state: "NY", phone: "(716) 485-3498", rating: 5, reviewCount: 20 },
  { businessName: "Beyond Beauty Salon & Spa", niche: "beauty", city: "Centerville", state: "IA", phone: "(641) 437-7048", rating: 4.9, reviewCount: 13 },
  { businessName: "Sherri Cobus EXP Realty, Brokerage", niche: "real_estate", city: "Renfrew", state: "ON", phone: "(613) 432-1947", rating: 5, reviewCount: 12 },
  { businessName: "Master Insurance LLC (Monte Vista)", niche: "insurance", city: "Monte Vista", state: "CO", phone: "(720) 776-0592", rating: 5, reviewCount: 8 },
  { businessName: "Electr'Iles Inc", niche: "electrical", city: "Cap-aux-Meules", state: "QC", phone: "(418) 986-5955", rating: 4.8, reviewCount: 5 },
  { businessName: "M T Poverty Well Drilling", niche: "well_water", city: "Lincoln", state: "MT", phone: "(406) 362-4536", rating: 4.8, reviewCount: 4 },
  { businessName: "Tyler Exploration", niche: "well_water", city: "Douglas", state: "WY", phone: "(307) 358-9300", rating: 5, reviewCount: 4 },
  { businessName: "Riverside Tree Services", niche: "tree", city: "Payette", state: "ID", phone: "(208) 642-1154", rating: 3, reviewCount: 4 },
  { businessName: "Burkhart Well Drilling & Pump", niche: "well_water", city: "Buhl", state: "ID", phone: "(208) 537-9945", rating: 4.5, reviewCount: 4 },
  { businessName: "McGowan Sewer Service LLC", niche: "plumbing", city: "", state: "MT", phone: "(406) 270-4340", rating: 4, reviewCount: 4 },
  { businessName: "Mc Leran Well Drilling LLC", niche: "well_water", city: "New Plymouth", state: "ID", phone: "(208) 941-2587", rating: 5, reviewCount: 4 },
  { businessName: "Green Heating & Air Conditioning", niche: "hvac", city: "Indianola", state: "MS", phone: "(662) 887-3683", rating: 5, reviewCount: 4 },
  { businessName: "BlueRidge Roofing Systems", niche: "roofing", city: "Garden City", state: "KS", phone: "(620) 265-5617", rating: 5, reviewCount: 4 },
  { businessName: "Baja Water Wells and Services", niche: "well_water", city: "Coeur d'Alene", state: "ID", phone: "(208) 755-8220", rating: 5, reviewCount: 4 },
  { businessName: "Sharp Drilling", niche: "well_water", city: "Sidney", state: "MT", phone: "(406) 482-5620", rating: 4.7, reviewCount: 3 },
  { businessName: "4 J Well Services Inc. Shop", niche: "well_water", city: "Baker", state: "MT", phone: "(406) 778-3856", rating: 5, reviewCount: 3 },
  { businessName: "Haskins Excavating Llc", niche: "excavating", city: "Superior", state: "MT", phone: "(406) 382-0090", rating: 4.7, reviewCount: 3 },
  { businessName: "Fritz's Septic", niche: "septic", city: "Torrington", state: "WY", phone: "(307) 532-2227", rating: 5, reviewCount: 3 },
  { businessName: "Roumell Plumbing & Heating Inc", niche: "plumbing", city: "Glenrock", state: "WY", phone: "(307) 436-9888", rating: 5, reviewCount: 3 },
  { businessName: "Levi Valdez Septic Tank Clg", niche: "plumbing", city: "Rupert", state: "ID", phone: "(208) 436-6774", rating: 4.7, reviewCount: 3 },
  { businessName: "Sweet's Sewer & Drain Cleaning", niche: "plumbing", city: "Bellevue", state: "ID", phone: "(208) 788-0245", rating: 5, reviewCount: 3 },
  { businessName: "Aspen Tree Service", niche: "tree", city: "Thermopolis", state: "WY", phone: "(307) 921-9420", rating: 5, reviewCount: 3 },
  { businessName: "Pep's Septic Pumping", niche: "septic", city: "Salmon", state: "ID", phone: "(208) 756-4697", rating: 5, reviewCount: 3 },
  { businessName: "Halifax Heating & Air Conditioning", niche: "hvac", city: "Halifax", state: "NS", phone: "(902) 450-5651", rating: 2.3, reviewCount: 3 },
  { businessName: "Triplett AC & Heating", niche: "hvac", city: "Cleveland", state: "MS", phone: "(662) 846-6252", rating: 5, reviewCount: 3 },
  { businessName: "Stasis Spa And Wellness", niche: "well_water", city: "Salem", state: "OH", phone: "(330) 257-8357", rating: 5, reviewCount: 3 },
  { businessName: "H & H Drilling", niche: "well_water", city: "Glendive", state: "MT", phone: "(406) 377-5952", rating: 4.5, reviewCount: 2 },
  { businessName: "Tim Schertel Tree Service", niche: "tree", city: "Libby", state: "MT", phone: "(406) 293-6781", rating: 5, reviewCount: 2 },
  { businessName: "Wild West Fencing", niche: "fence", city: "", state: "WY", phone: "(307) 259-0809", rating: 5, reviewCount: 2 },
  { businessName: "Swenson Drilling Inc.", niche: "well_water", city: "Sidney", state: "MT", phone: "(406) 488-1270", rating: 5, reviewCount: 1 },
  { businessName: "Central Kansas Roofing LLC", niche: "roofing", city: "Gorham", state: "KS", phone: "(785) 483-0486", rating: 0, reviewCount: 0 },
  { businessName: "Patriot Roofing and Restoration", niche: "roofing", city: "Long Island", state: "KS", phone: "(785) 543-0387", rating: 0, reviewCount: 0 },
  { businessName: "Trisler Landscape Inc.", niche: "landscaping", city: "Jackson", state: "MS", phone: "(601) 977-9082", rating: 4.2, reviewCount: 17 },
  { businessName: "Circle T Truck Wash", niche: "pressure_wash", city: "Jerome", state: "ID", phone: "(208) 329-9495", rating: 4.2, reviewCount: 15 },
  { businessName: "307 Surface Solutions", niche: "pressure_wash", city: "", state: "WY", phone: "(307) 461-9702", rating: 5, reviewCount: 14 },
  { businessName: "Great Plains Landscape & Design", niche: "landscaping", city: "Beloit", state: "KS", phone: "(785) 738-2016", rating: 4.5, reviewCount: 10 },
  { businessName: "Clean Fibers LLC", niche: "cleaning", city: "Colstrip", state: "MT", phone: "(406) 901-7762", rating: 5, reviewCount: 8 },
  { businessName: "Cold Smoke Cleaners", niche: "cleaning", city: "", state: "MT", phone: "(406) 902-9247", rating: 5, reviewCount: 8 },
  { businessName: "Lawnco Lawn Services", niche: "landscaping", city: "Norfolk", state: "NE", phone: "(402) 379-0506", rating: 4.8, reviewCount: 6 },
  { businessName: "Cyrene lawn care and maintenance", niche: "landscaping", city: "Houston", state: "MS", phone: "(662) 542-1624", rating: 5, reviewCount: 6 },
  { businessName: "FLM Lawn Care and Landscaping", niche: "landscaping", city: "Pine Bluff", state: "AR", phone: "(870) 592-8743", rating: 3.4, reviewCount: 5 },
  { businessName: "Levi King Concrete & Construction", niche: "construction", city: "Payette", state: "ID", phone: "(208) 739-2268", rating: 4.8, reviewCount: 51 },
  { businessName: "Lange Insurance Agency", niche: "insurance", city: "Grants", state: "NM", phone: "(505) 285-6063", rating: 4.7, reviewCount: 45 },
  { businessName: "New Spring Breeze Spa", niche: "beauty", city: "Key Largo", state: "FL", phone: "(305) 735-4503", rating: 5, reviewCount: 43 },
  { businessName: "Lucid Terra", niche: "landscaping", city: "Tyler", state: "TX", phone: "(903) 213-5525", rating: 4.9, reviewCount: 41 },
  { businessName: "Yeny Masajes Linfático Spa", niche: "beauty", city: "Florida City", state: "FL", phone: "(786) 236-6552", rating: 5, reviewCount: 28 },
  { businessName: "spring breeze spa", niche: "beauty", city: "Tavernier", state: "FL", phone: "(305) 916-5063", rating: 5, reviewCount: 21 },
  { businessName: "Brooks Kansas City Electric Services Inc.", niche: "electrical", city: "Kansas City", state: "KS", phone: "", rating: 4.9, reviewCount: 15 },
  { businessName: "Barham Heating & Air Conditioning", niche: "hvac", city: "McGehee", state: "AR", phone: "", rating: 4.2, reviewCount: 5 },
  { businessName: "Trash Bin Cleaning", niche: "pressure_wash", city: "", state: "WY", phone: "(307) 369-3114", rating: 4.8, reviewCount: 4 },
  { businessName: "JESUS Solutions LLC", niche: "junk_removal", city: "", state: "WY", phone: "(307) 622-7744", rating: 5, reviewCount: 4 },
  { businessName: "G&G Landscaping Services Inc.", niche: "landscaping", city: "Hailey", state: "ID", phone: "(208) 788-1708", rating: 5, reviewCount: 4 },
  { businessName: "Grasshopper lawn care", niche: "landscaping", city: "Parkersburg", state: "WV", phone: "(304) 615-3540", rating: 4.3, reviewCount: 4 },
  { businessName: "Stryker's on Doody", niche: "junk_removal", city: "", state: "WY", phone: "(307) 881-2675", rating: 5, reviewCount: 3 },
  { businessName: "Eagle Cliff Dumpster and Trailer Services", niche: "junk_removal", city: "", state: "WY", phone: "(307) 680-1970", rating: 5, reviewCount: 3 },
  { businessName: "Four Seasons Lawn Care", niche: "landscaping", city: "Norfolk", state: "NE", phone: "(402) 992-6415", rating: 5, reviewCount: 3 },
  { businessName: "Jv patios & landscaping", niche: "landscaping", city: "", state: "", phone: "(787) 408-1730", rating: 4, reviewCount: 3 },
  { businessName: "Dependable Dumpster Rentals Chinook", niche: "junk_removal", city: "Chinook", state: "MT", phone: "(406) 201-2708", rating: 4.5, reviewCount: 2 },
  { businessName: "Best Landscaping", niche: "landscaping", city: "Marietta", state: "OH", phone: "(740) 373-5922", rating: 5, reviewCount: 2 },
  { businessName: "M&M Landscape and Lawn, Inc.", niche: "landscaping", city: "Sage", state: "AR", phone: "(870) 368-5522", rating: 5, reviewCount: 2 },
  { businessName: "The Ranches Landscaping LLC", niche: "landscaping", city: "Indianapolis", state: "IN", phone: "(317) 200-4088", rating: 5, reviewCount: 1 },
  { businessName: "Triple L Lawns Landscaping & Labor", niche: "landscaping", city: "Belpre", state: "OH", phone: "(304) 483-3785", rating: 5, reviewCount: 1 },
  { businessName: "Terry Fraser Landscape Planning", niche: "landscaping", city: "Kenora", state: "ON", phone: "(807) 468-1270", rating: 4, reviewCount: 1 },
  { businessName: "X-Pert Lawn & Landscaping", niche: "landscaping", city: "Hartington", state: "NE", phone: "(402) 254-6202", rating: 5, reviewCount: 1 },
  { businessName: "Jueden Lawn Services", niche: "landscaping", city: "Hartington", state: "NE", phone: "(402) 254-6339", rating: 5, reviewCount: 1 },
  { businessName: "J D Lawncare Services ( Jerome Dunnigan)", niche: "landscaping", city: "Columbus", state: "MS", phone: "(662) 352-5115", rating: 5, reviewCount: 1 },
  { businessName: "M Duguay Landscaping", niche: "landscaping", city: "Allardville Parish", state: "NB", phone: "(506) 252-6272", rating: 5, reviewCount: 1 },
  { businessName: "Bemidji Insurance Plus", niche: "insurance", city: "Bemidji", state: "MN", phone: "(218) 751-3771", rating: 4.3, reviewCount: 18 },
  { businessName: "Insurance Corporation of Belize & Nationwide Cash Express Santa Elena Branch", niche: "insurance", city: "", state: "", phone: "(501) 824-2540", rating: 4.3, reviewCount: 12 },
  { businessName: "Kim Kroner REALTOR", niche: "real_estate", city: "Ashburn", state: "VA", phone: "(703) 946-2526", rating: 5, reviewCount: 12 },
  { businessName: "360 Insurance", niche: "insurance", city: "Monte Vista", state: "CO", phone: "(719) 852-8840", rating: 4.9, reviewCount: 11 },
  { businessName: "Insurance Corporation of Belize & Nationwide Cash Express Seine Bight Agency", niche: "insurance", city: "", state: "", phone: "(501) 523-3555", rating: 4.3, reviewCount: 11 },
  { businessName: "Chelsea's Spa", niche: "beauty", city: "Fairfield", state: "IA", phone: "(641) 451-4259", rating: 5, reviewCount: 11 },
  { businessName: "RF&G Insurance Company Ltd. Agency - J.O. Espejo Agent", niche: "insurance", city: "", state: "", phone: "(501) 822-0958", rating: 4.6, reviewCount: 9 },
  { businessName: "Lonetree Inspections and Repairs", niche: "construction", city: "Green River", state: "WY", phone: "(307) 870-6110", rating: 5, reviewCount: 8 },
  { businessName: "Cedar Rose Spa", niche: "beauty", city: "Fairfield", state: "IA", phone: "(641) 209-9725", rating: 5, reviewCount: 8 },
  { businessName: "JMF Services, Inc", niche: "septic", city: "Libby", state: "MT", phone: "(406) 293-7588", rating: 5, reviewCount: 7 },
  { businessName: "Harber Construction", niche: "construction", city: "Pinedale", state: "WY", phone: "(307) 231-4300", rating: 5, reviewCount: 7 },
  { businessName: "Secure Care Health Insurance SD", niche: "insurance", city: "Pierre", state: "SD", phone: "(605) 204-9939", rating: 5, reviewCount: 7 },
  { businessName: "Taylor Heat & Air", niche: "hvac", city: "Boyle", state: "MS", phone: "(662) 843-8844", rating: 3.4, reviewCount: 7 },
  { businessName: "Lafleur Gardens Ltd", niche: "landscaping", city: "Timmins", state: "ON", phone: "(705) 268-2323", rating: 3.6, reviewCount: 7 },
  { businessName: "Faltree Farm", niche: "retail", city: "Loma", state: "MT", phone: "(406) 696-7339", rating: 5, reviewCount: 6 },
  { businessName: "The AC BOX", niche: "hvac", city: "", state: "", phone: "(876) 451-1689", rating: 5, reviewCount: 6 },
  { businessName: "Hairband The", niche: "beauty", city: "Terrace Bay", state: "ON", phone: "(807) 825-4247", rating: 4.7, reviewCount: 6 },
  { businessName: "Sorlie Septic Services", niche: "septic", city: "Trout Creek", state: "MT", phone: "(406) 827-0888", rating: 4.2, reviewCount: 5 },
  { businessName: "Staggs Contracting LLC", niche: "construction", city: "", state: "MT", phone: "(406) 595-6555", rating: 4.2, reviewCount: 5 },
  { businessName: "M Diamond Drilling", niche: "well_water", city: "Bozeman", state: "MT", phone: "(406) 586-8104", rating: 5, reviewCount: 5 },
  { businessName: "Architecture 1er Plan & Déco", niche: "construction", city: "", state: "", phone: "", rating: 0, reviewCount: 0 },
  { businessName: "Harold Multi services", niche: "construction", city: "", state: "", phone: "", rating: 0, reviewCount: 0 },
  { businessName: "Re/Max Generations Realty", niche: "real_estate", city: "Marathon", state: "ON", phone: "", rating: 0, reviewCount: 0 },
  { businessName: "Hillman Drilling", niche: "well_water", city: "Livingston", state: "MT", phone: "(406) 222-9355", rating: 0, reviewCount: 0 },
  { businessName: "TC HVAC", niche: "hvac", city: "Randolph", state: "NE", phone: "(402) 360-0555", rating: 0, reviewCount: 0 },
  { businessName: "TIENDA AXA OAXACA", niche: "insurance", city: "", state: "", phone: "", rating: 3.8, reviewCount: 43 },
  { businessName: "Tamietti House Moving-Construction", niche: "junk_removal", city: "Whitehall", state: "MT", phone: "(406) 494-2678", rating: 4, reviewCount: 4 },
  { businessName: "Chalk Buttes Landscaping", niche: "landscaping", city: "Douglas", state: "WY", phone: "(307) 358-4595", rating: 5, reviewCount: 4 },
  { businessName: "BAMN Junk Removal and Moving LLC", niche: "junk_removal", city: "", state: "MT", phone: "(406) 623-1326", rating: 5, reviewCount: 3 },
  { businessName: "Central MS Landscaping", niche: "landscaping", city: "Brandon", state: "MS", phone: "(601) 942-9363", rating: 5, reviewCount: 3 },
  { businessName: "Air Now", niche: "hvac", city: "Key Largo", state: "FL", phone: "(305) 684-7971", rating: 5, reviewCount: 18 },
  { businessName: "Classicut Hair Design", niche: "beauty", city: "Nipigon", state: "ON", phone: "(807) 887-3061", rating: 4.9, reviewCount: 14 },
  { businessName: "Home Protector Insurance Agency, Santa Elena Town", niche: "insurance", city: "", state: "", phone: "(501) 660-1928", rating: 5, reviewCount: 11 },
  { businessName: "S & B Services", niche: "accounting", city: "Chillicothe", state: "MO", phone: "(660) 707-1040", rating: 4.4, reviewCount: 9 },
  { businessName: "Excel Drilling", niche: "well_water", city: "Bozeman", state: "MT", phone: "(406) 994-0092", rating: 5, reviewCount: 9 },
  { businessName: "Producers Choice LLC", niche: "insurance", city: "Pierre", state: "SD", phone: "(605) 989-2102", rating: 5, reviewCount: 8 },
  { businessName: "Dave Johnson Insurance", niche: "insurance", city: "Pierre", state: "SD", phone: "(605) 972-1013", rating: 5, reviewCount: 7 },
  { businessName: "V & M AC & Refrigeration Distributors, LLC", niche: "hvac", city: "", state: "", phone: "(876) 952-8347", rating: 4.7, reviewCount: 6 },
  { businessName: "Excel property maintenance", niche: "construction", city: "", state: "", phone: "(732) 520-0055", rating: 5, reviewCount: 5 },
  { businessName: "Letram Enterprises", niche: "trucking_auto", city: "Cheyenne", state: "WY", phone: "(307) 514-3695", rating: 5, reviewCount: 5 },
  { businessName: "Fournier Construction LLC", niche: "construction", city: "Sandpoint", state: "ID", phone: "(208) 265-8935", rating: 5, reviewCount: 4 },
  { businessName: "Les Pouces Verts de la Montagne", niche: "landscaping", city: "Saint-Gabriel-de-Rimouski", state: "QC", phone: "(418) 798-4551", rating: 4, reviewCount: 4 },
  { businessName: "Divert Gazon Enr", niche: "landscaping", city: "Rimouski", state: "QC", phone: "(418) 724-4099", rating: 4, reviewCount: 4 },
  { businessName: "Vision Credit Union", niche: "finance", city: "Consort", state: "AB", phone: "(403) 577-2650", rating: 4.3, reviewCount: 4 },
  { businessName: "Albuquerque's Affordable Insurance Agency", niche: "insurance", city: "Albuquerque", state: "NM", phone: "(510) 605-3168", rating: 5, reviewCount: 4 },
  { businessName: "I Q Construction", niche: "construction", city: "Laramie", state: "WY", phone: "(307) 761-0042", rating: 5, reviewCount: 4 },
  { businessName: "Greenacre Excavation and Welding Inc", niche: "excavating", city: "Powell", state: "WY", phone: "(307) 296-6407", rating: 5, reviewCount: 3 },
  { businessName: "Eason Insurance Service Inc", niche: "insurance", city: "Tonopah", state: "NV", phone: "(775) 482-6221", rating: 3.7, reviewCount: 3 },
  { businessName: "Lamoille Valley Insurance Agency", niche: "insurance", city: "Johnson", state: "VT", phone: "(802) 635-9220", rating: 5, reviewCount: 3 },
  { businessName: "Yves Rochefort", niche: "insurance", city: "Val-d'Or", state: "QC", phone: "(819) 850-6354", rating: 4, reviewCount: 3 },
  { businessName: "Air Pro Inc", niche: "hvac", city: "Chibougamau", state: "QC", phone: "(418) 770-7227", rating: 3.3, reviewCount: 3 },
  { businessName: "Northern Chautaqua Realty Inc", niche: "real_estate", city: "Fredonia", state: "NY", phone: "(716) 672-7222", rating: 5, reviewCount: 3 },
  { businessName: "ZMC Massage", niche: "beauty", city: "Ashburn", state: "VA", phone: "(703) 220-4033", rating: 5, reviewCount: 3 },
  { businessName: "Gestion Loiselle Inc", niche: "snow_removal", city: "Baie-Comeau", state: "QC", phone: "(418) 296-4448", rating: 4.5, reviewCount: 2 },
  { businessName: "Points West Insurance", niche: "insurance", city: "Kimball", state: "NE", phone: "(308) 235-2821", rating: 5, reviewCount: 2 },
  { businessName: "Nadeau Refrigeration Enrg", niche: "hvac", city: "Fatima", state: "QC", phone: "(418) 986-2237", rating: 5, reviewCount: 2 },
  { businessName: "Bonair Ventilation", niche: "hvac", city: "Saint-Étienne-des-Grès", state: "QC", phone: "(819) 374-5253", rating: 5, reviewCount: 2 },
  { businessName: "Serenity Now Day Spa", niche: "beauty", city: "Centerville", state: "IA", phone: "(641) 856-6691", rating: 5, reviewCount: 2 },
  { businessName: "e3 Tax Service", niche: "accounting", city: "Kirksville", state: "MO", phone: "(660) 627-0900", rating: 5, reviewCount: 2 },
  { businessName: "JH Tax and Accounting LLC.", niche: "accounting", city: "Moberly", state: "MO", phone: "(660) 263-3388", rating: 5, reviewCount: 2 },
  { businessName: "331 Sport & Nature Inc.", niche: "retail", city: "Memramcook", state: "NB", phone: "(506) 233-9153", rating: 5, reviewCount: 1 },
  { businessName: "Entreprises D Lebrun", niche: "snow_removal", city: "Amqui", state: "QC", phone: "(418) 629-5855", rating: 3, reviewCount: 1 },
  { businessName: "Baudette Agency", niche: "insurance", city: "Baudette", state: "MN", phone: "(218) 634-1872", rating: 5, reviewCount: 1 },
  { businessName: "John White Insurance", niche: "insurance", city: "Sidney", state: "NE", phone: "(308) 254-0283", rating: 5, reviewCount: 1 },
  { businessName: "Terry Tharp Nationwide Insurance", niche: "insurance", city: "Little Rock", state: "AR", phone: "(501) 224-7666", rating: 5, reviewCount: 1 },
  { businessName: "Mefferd Agency-Farmers Union Insurance-Andrew Mefferd", niche: "insurance", city: "Pierre", state: "SD", phone: "(605) 222-7979", rating: 5, reviewCount: 1 },
  { businessName: "At The Point Insurance Services, Inc.", niche: "insurance", city: "San Diego", state: "CA", phone: "(619) 693-6105", rating: 5, reviewCount: 1 },
  { businessName: "Madawaska Energy Solutions Inc", niche: "hvac", city: "Edmundston", state: "NB", phone: "(506) 740-4336", rating: 5, reviewCount: 1 },
  { businessName: "El Cerro Garden", niche: "landscaping", city: "", state: "", phone: "(939) 339-9852", rating: 5, reviewCount: 1 },
  { businessName: "Aménagement JMS", niche: "landscaping", city: "Sainte-Monique", state: "QC", phone: "(581) 230-0707", rating: 1, reviewCount: 1 },
  { businessName: "Moody Roots", niche: "landscaping", city: "Thunder Bay", state: "ON", phone: "(807) 474-6893", rating: 5, reviewCount: 1 },
  { businessName: "Keratinas Roxi", niche: "beauty", city: "", state: "", phone: "(535) 691-9929", rating: 5, reviewCount: 1 },
  { businessName: "Spa Terra", niche: "beauty", city: "Monroe", state: "LA", phone: "(318) 600-4364", rating: 5, reviewCount: 1 },
  { businessName: "Sayre & Associates", niche: "accounting", city: "Milan", state: "MO", phone: "(660) 265-4624", rating: 5, reviewCount: 1 },
  { businessName: "R5 Roofing, Llc", niche: "roofing", city: "Hays", state: "KS", phone: "", rating: 0, reviewCount: 0 },
  { businessName: "Green Thumb Landscaping", niche: "landscaping", city: "Norfolk", state: "NE", phone: "", rating: 5, reviewCount: 1 },
  { businessName: "ASESORES MONTOYA", niche: "insurance", city: "", state: "", phone: "", rating: 4.5, reviewCount: 13 },
  { businessName: "Home protector insurance", niche: "insurance", city: "", state: "", phone: "", rating: 4.9, reviewCount: 9 },
  { businessName: "Inbursa", niche: "insurance", city: "", state: "", phone: "", rating: 3.8, reviewCount: 8 },
  { businessName: "Met Life", niche: "insurance", city: "", state: "", phone: "", rating: 4.1, reviewCount: 8 },
  { businessName: "MetLife Plaza Santa Elena", niche: "insurance", city: "", state: "", phone: "", rating: 5, reviewCount: 7 },
  { businessName: "Leben Life", niche: "insurance", city: "", state: "", phone: "", rating: 3.4, reviewCount: 5 },
  { businessName: "Ins & Outs", niche: "excavating", city: "Greers Ferry", state: "AR", phone: "(501) 270-9102", rating: 5, reviewCount: 4 },
  { businessName: "Overland SR22 Insurance Agency - Texas", niche: "insurance", city: "El Paso", state: "TX", phone: "(915) 339-9753", rating: 5, reviewCount: 4 },
  { businessName: "Devost Refrigeration \"2010\" Inc.", niche: "hvac", city: "Grand-Sault", state: "NB", phone: "(506) 473-1274", rating: 4, reviewCount: 4 },
  { businessName: "Mari Trosclair, Real Estate Consultant", niche: "real_estate", city: "Pittsboro", state: "NC", phone: "(919) 619-2236", rating: 5, reviewCount: 4 },
  { businessName: "Sherry full body massage and spa", niche: "beauty", city: "Tyler", state: "TX", phone: "(213) 608-9027", rating: 3, reviewCount: 4 },
  { businessName: "Quality Septic & Sewer Services", niche: "septic", city: "Miles City", state: "MT", phone: "(406) 234-1710", rating: 5, reviewCount: 3 },
  { businessName: "Stunley Gardens", niche: "landscaping", city: "Foresters Falls", state: "ON", phone: "(613) 646-7364", rating: 5, reviewCount: 3 },
  { businessName: "ABC Tax Prep Service LLC", niche: "accounting", city: "Brookfield", state: "MO", phone: "(660) 214-0691", rating: 5, reviewCount: 3 },
  { businessName: "John w Gillum LLC", niche: "accounting", city: "Kirksville", state: "MO", phone: "(660) 627-1259", rating: 5, reviewCount: 3 },
  { businessName: "Assurances Roy & Thiboutot Inc", niche: "insurance", city: "Val-d'Or", state: "QC", phone: "(819) 825-2999", rating: 3.5, reviewCount: 2 },
  { businessName: "Alexandria Refrigeration", niche: "hvac", city: "Alexandria", state: "MN", phone: "(320) 762-0585", rating: 5, reviewCount: 2 },
  { businessName: "Assurances Guy Rochefort", niche: "insurance", city: "Val-d'Or", state: "QC", phone: "(819) 825-6052", rating: 5, reviewCount: 1 },
  { businessName: "Climat-Lac Inc", niche: "hvac", city: "Roberval", state: "QC", phone: "(418) 275-5445", rating: 5, reviewCount: 1 },
  { businessName: "Pelletier Sheet Metal", niche: "hvac", city: "Edmundston", state: "NB", phone: "(506) 735-4504", rating: 5, reviewCount: 1 },
  { businessName: "DESIGN PAYSAGE", niche: "landscaping", city: "Roberval", state: "QC", phone: "(418) 275-0751", rating: 5, reviewCount: 1 },
  { businessName: "Sara A. Anderson Agency Inc.", niche: "insurance", city: "Blackduck", state: "MN", phone: "(218) 835-7711", rating: 0, reviewCount: 0 },
  { businessName: "Halpenny Agencies", niche: "insurance", city: "", state: "", phone: "(403) 326-3818", rating: 0, reviewCount: 0 },
  { businessName: "Paysagement R.Blouin", niche: "landscaping", city: "Roberval", state: "QC", phone: "(819) 574-0491", rating: 0, reviewCount: 0 },
  { businessName: "GNP Destino Seguros", niche: "insurance", city: "", state: "", phone: "", rating: 4.5, reviewCount: 8 },
  { businessName: "PROMARQ Asesores Patrimoniales", niche: "insurance", city: "", state: "", phone: "", rating: 5, reviewCount: 8 },
  { businessName: "Click Seguros, Agente de Seguros y Fianzas. PACHUCA", niche: "insurance", city: "", state: "", phone: "", rating: 5, reviewCount: 5 },
  { businessName: "Grupo Nacional Provincial", niche: "insurance", city: "", state: "", phone: "", rating: 4, reviewCount: 4 },
  { businessName: "Home Protector Insurance Agent", niche: "insurance", city: "", state: "", phone: "(501) 625-0756", rating: 0, reviewCount: 0 },
  { businessName: "FrostFlow Ac Services", niche: "hvac", city: "", state: "", phone: "(876) 841-0273", rating: 0, reviewCount: 0 },
  { businessName: "SALON KENIA", niche: "beauty", city: "", state: "", phone: "(535) 524-5297", rating: 0, reviewCount: 0 },
  { businessName: "Frantz Le Jardinier", niche: "landscaping", city: "", state: "", phone: "", rating: 5, reviewCount: 2 },
];
